### ISSUE TITLE
mkvcage.ws

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#15]
## Summary

This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
mkvcage.ws   CNAME . ; DomainSharks
*.mkvcage.ws   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
```
whois mkvcage.ws
Domain Name: MKVCAGE.WS
Domain ID: 67ED5633962A4E7BE050010AAC01EAB1
WHOIS Server: whois.namecheap.com
Registrar URL: https://www.namecheap.com/domains/whois.aspx
Updated Date: 2019-04-16T15:56:51Z
Creation Date: 2018-05-17T00:29:49Z
Registrar Registration Expiration Date: 2020-05-17T00:29:49Z
Registrar: Namecheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Domain Status: clientTransferProhibited
Name Server: dns1.registrar-servers.com
Name Server: dns2.registrar-servers.com
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72128943-c6a2c380-3374-11ea-943e-aece44329146.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [ ] Added to Source file
