### ISSUE TITLE
hostingfreelife.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#16]
## Summary

This 'Malicious' domain have to be blocked as..

- [ ] [Single Domain](source/malicious/domains.list)
- [x] [Wild carded](source/malicious/wildcard.list)

```python
hostingfreelife.com   CNAME . ; Malicious, AdWare
*.hostingfreelife.com   CNAME . ; Malicious, AdWare
d1pj5e2gy6w2jc.cloudfront.net   CNAME . ; Malicious, AdWare
d3dkhq0wwdwodv.cloudfront.net   CNAME . ; Malicious, AdWare
```

... ***because***:

## Relevant logs and/or screenshots

https://www.myantispyware.com/2018/12/28/how-to-remove-hostingfreelife-com-pop-ups-chrome-firefox-ie-edge/

https://www.fixyourbrowser.com/removal-instructions/popups/hostingfreelife-com-removal/

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/72129509-cc010d80-3376-11ea-915a-9bdf66fbed3d.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team @Spirillen)
- [X] Added to Source file
