### ISSUE TITLE
sadsokz.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#164]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
sadsokz.com   CNAME . ; AdWare, Tracking
*.sadsokz.com   CNAME . ; AdWare, Tracking
```

## Relevant logs and/or screenshots
> This URL is used by Adsterra Advertising Network for ad serving.

Try on #162 and all links would be infected like

```
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r
http://sadsokz.com/w0brfp2d7?glhywu=85&refer=https%3A%2F%2Fgor03.ru%2F&kw=%5B%22nude%22%2C%22teen%22%2C%22girls%22%2C%22-%22%2C%22free%22%2C%22young%22%2C%22xxx%22%2C%22videos%22%2C%22with%22%2C%22sexy%22%2C%2218%22%2C%22yo%22%2C%22babes%22%2C%22gor03%22%2C%22ru%22%5D&key=883d7aa76438bded6903a5749b6581bf&scrWidth=1920&scrHeight=1080&tz=1&ship=&pst=&v=19.12.v.10&res=7.31&dev=r

```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/73161712-781f5400-40ec-11ea-8401-16c394e007fe.png)

![image](https://user-images.githubusercontent.com/44526987/73161849-bcaaef80-40ec-11ea-8c0d-258596c8be8d.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [X] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
