### ISSUE TITLE
histats.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#17]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
histats.com   CNAME . ; Tracking
*.histats.com   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

> Start tracking your visitors in 1 minute!
>   * Pick a counter or hidden tracker.

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72180536-abbd6700-33e7-11ea-8037-21379dfdc1ec.png)

</details>

## RPZ History
<details><Summary>RPZ Zone</summary>

histats.com.ero-advertising.com.rpz.mypdns.cloud
s10.histats.com.ero-advertising.com.rpz.mypdns.cloud
histats.com.rpz.mypdns.cloud
s10.histats.com.rpz.mypdns.cloud
s11.histats.com.rpz.mypdns.cloud
sstatic1.histats.com.rpz.mypdns.cloud
s4.histats.com.rpz.mypdns.cloud
s5.histats.com.rpz.mypdns.cloud
s128.histats.com.rpz.mypdns.cloud
s4is.histats.com.rpz.mypdns.cloud
s129js.histats.com.rpz.mypdns.cloud
www.histats.com.rpz.mypdns.cloud

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
