### ISSUE TITLE
ero-advertising.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#18]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
ero-advertising.com   CNAME . ; AdWare
*.ero-advertising.com   CNAME . ; AdWare
```

... ***because***:

## Relevant logs and/or screenshots
This domains should need a lot of explanation :smiling_imp: 

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72181141-f1c6fa80-33e8-11ea-943c-554a70e97582.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [X] Added to Source file
