### ISSUE TITLE
wetmeets.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#193]
## Summary
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
wetmeets.com   CNAME . ; Adult
*.wetmeets.com   CNAME . ; Adult
i.wetmeets.com   CNAME . ; AdWare
```

### additional for hosts
```shell

www.
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/73480575-6bc02300-439a-11ea-876f-78793d29a816.png)

</details>

## Logger output
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | i.wetmeets.com | 1 | image | `http://i.wetmeets.com/favicon.ico` |
| +2 |  |  | i.wetmeets.com | 3 | xhr | `https://tdsjsext3.com/ExtService.svc/getextparams` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/media/exit-new/exit1.js` |
| +1 |  |  | i.wetmeets.com | 1 | css | `http://i.wetmeets.com/media/exit-new/exit-popup.css` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/media/bb.js` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/media/dating/tinderv2/js/trls.js` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/util/utils.js` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/cookie/js.cookie.js` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/media/dating/tinderv2/js/vegas.js` |
| +1 |  |  | i.wetmeets.com | 1 | script | `http://i.wetmeets.com/media/dating/tinderv2/js/jquery.js` |
| +1 |  |  | i.wetmeets.com | 1 | css | `http://i.wetmeets.com/media/dating/tinderv2/css/vegas.css` |
| +1 |  |  | i.wetmeets.com | 1 | css | `http://i.wetmeets.com/media/dating/tinderv2/css/animate.css` |
| +1 |  |  | i.wetmeets.com | 1 | css | `http://i.wetmeets.com/media/dating/tinderv2/css/style.css` |
| +1 |  |  | i.wetmeets.com | 1 | css | `http://i.wetmeets.com/media/dating/tinderv2/css/bootstrap.min.css` |
| +1 | \|\|googleapis.com^$important | -- | i.wetmeets.com | 3 | css | `https://fonts.googleapis.com/css?family=Roboto:400,300,700\|Raleway:400,700&subset=latin,cyrillic` |
| +0 |  |  | i.wetmeets.com | 1 | doc | `http://i.wetmeets.com/?u=eqqw2k7&o=7avk95x&t=r_wetmeets` |
| +0 |  |  | wetmeets.com | 1 | doc | `http://wetmeets.com/` |
</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](/mypdns/matrix/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](/mypdns/matrix/pulls) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
