### ISSUE TITLE
allbouttruth.info

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#208]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
allbouttruth.info   CNAME . ; AdWare, Tracking
*.allbouttruth.info   CNAME . ; AdWare, Tracking
```

## Relevant logs and/or screenshots
`allbouttruth.info` redirects to `https://www.one.com/en/?utm_source=tradedoubler&utm_campaign=tradedoubler_tradedoubler_nl&utm_medium=AFFILIATE`

See also:  https://github.com/easylist/easylist/pull/4849/files#diff-4903e7590de76df1abe1703921a2c88bR886

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [x] Added to Source file
