### ISSUE TITLE
telkomuniversity.ac.id

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#209]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [ ] [Wildcarded](source/adware/wildcard.list)
- [X] [Single domain blocking](source/adware/domains.list)

```python
student.telkomuniversity.ac.id   CNAME . ; AdWare
dmm.telkomuniversity.ac.id   CNAME . ; AdWare
```

## Relevant logs and/or screenshots
The following domains are involved in spam

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/73612701-44fa2a80-45ee-11ea-9eec-e593fc526edc.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [x] RPZ Server (Team @Spirillen)
- [x] Added to Source file

**Comment by spirillen** [comment]
There would also be `bid.telkomuniversity.ac.id`
