### ISSUE TITLE
go-mpulse.net

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#21]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
go-mpulse.net   CNAME . ; Tracking
*.go-mpulse.net   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

```
Filter: ||go-mpulse.net^$3p
Filter list: AdGuard Tracking Protection 
             EasyPrivacy
```

<details><Summary>RPZ History</summary>

```
go-mpulse.net.rpz.mypdns.cloud
36fb6d10.go-mpulse.net.rpz.mypdns.cloud
3409b6b0.go-mpulse.net.rpz.mypdns.cloud
36eb5491.go-mpulse.net.rpz.mypdns.cloud
3211c0e1.go-mpulse.net.rpz.mypdns.cloud
36ebc202.go-mpulse.net.rpz.mypdns.cloud
3409bcb2.go-mpulse.net.rpz.mypdns.cloud
36a3fec2.go-mpulse.net.rpz.mypdns.cloud
s2.go-mpulse.net.rpz.mypdns.cloud
c-lt2.go-mpulse.net.rpz.mypdns.cloud
3408f623.go-mpulse.net.rpz.mypdns.cloud
36cc2473.go-mpulse.net.rpz.mypdns.cloud
c-lt3.go-mpulse.net.rpz.mypdns.cloud
36ebc234.go-mpulse.net.rpz.mypdns.cloud
36f11e95.go-mpulse.net.rpz.mypdns.cloud
36d71176.go-mpulse.net.rpz.mypdns.cloud
36fb6d09.go-mpulse.net.rpz.mypdns.cloud
ae810539.go-mpulse.net.rpz.mypdns.cloud
36f11e49.go-mpulse.net.rpz.mypdns.cloud
36a3fe4a.go-mpulse.net.rpz.mypdns.cloud
36cc246a.go-mpulse.net.rpz.mypdns.cloud
3408178b.go-mpulse.net.rpz.mypdns.cloud
3409119b.go-mpulse.net.rpz.mypdns.cloud
c.go-mpulse.net.rpz.mypdns.cloud
364bf52c.go-mpulse.net.rpz.mypdns.cloud
36f11e2c.go-mpulse.net.rpz.mypdns.cloud
d.go-mpulse.net.rpz.mypdns.cloud
364bf52d.go-mpulse.net.rpz.mypdns.cloud
36f1f23d.go-mpulse.net.rpz.mypdns.cloud
364bf52e.go-mpulse.net.rpz.mypdns.cloud
36f1f08e.go-mpulse.net.rpz.mypdns.cloud
364bf5fe.go-mpulse.net.rpz.mypdns.cloud
s.go-mpulse.net.rpz.mypdns.cloud
s2-test.go-mpulse.net.rpz.mypdns.cloud
```

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
