### ISSUE TITLE
lgsvywogylblv.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#214]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
lgsvywogylblv.com   CNAME . ; AdWare
*.lgsvywogylblv.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

https://github.com/easylist/easylist/commit/2a2a8985ddc75dfe9e1bdc4222516e8615c72419#diff-4903e7590de76df1abe1703921a2c88bR9413

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
