### ISSUE TITLE
admp-tc-bauer.adtlgc.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#216]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [ ] [Wildcarded](source/adware/wildcard.list)
- [X] [Single domain blocking](source/adware/domains.list)

```python
admp-tc-bauer.adtlgc.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots
Encountered on `kaleva.fi`

<https://github.com/easylist/easylist/pull/4871/files#diff-4903e7590de76df1abe1703921a2c88bR452>

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [x] RPZ Server (Team @Spirillen)
- [x] Added to Source file

**Comment by spirillen** [comment]
The domain name of this submission `admp-tc-bauer.adtlgc.com` gives me the impression that it should/would be possible to block `adtlgc.com` entirely. If you try to visit that domain, you just get a timeout()

See also: <https://github.com/easylist/easylist/pull/4871/files#issuecomment-583758278>

**Comment by spirillen** [comment]
From the [rpz.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#rpz.mypdns.cloud) we find a lot of existent records that indicates the ability to actually block this submission at second level.

#### RPZ history
|name|type|content|
|----|----|-------|
|adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|svd2.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|code2.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|core2.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|svd.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|code.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|enirocode.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|enirodk.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|stampen.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|keywords.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|abseckw.adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|`www.adtlgc.com.rpz.mypdns.cloud`|CNAME|.|

**Comment by spirillen** [comment]
From the [external hosts-sources](https://gitlab.com/my-privacy-dns/external-sources/hosts-sources) we find these records

```
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:abseckw.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:code.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:code2.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:core2.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:enirocode.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:enirodk.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:keywords.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:stampen.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:svd.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:svd2.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/someonewhocares/domain.list:www.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/hphosts_ad_servers/domain.list:adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-bauer.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-delfilt.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-digo.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-eluniversal.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-gaca.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-hegnar.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-ipm.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-larepublica.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-lrytas.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-mediahuis.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-oecd.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-pmp.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-sati.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-tmg.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:admp-tc-vlmedia.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/adaway/domain.list:code3.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/mvps/domain.list:code.adtlgc.com
My Privacy DNS Firewall/hosts-sources/data/mvps/domain.list:code2.adtlgc.com
```

The interesting here is that [someonewhocares](https://someonewhocares.org/hosts/) and @fademind [hphosts_ad_servers](https://github.com/FadeMind/hosts.extras) have chosen to block this domain from the root level.

We keep the history here and block this at second level as


```python
adtlgc.com   CNAME . ; AdWare
*.adtlgc.com   CNAME . ; AdWare
```

The new RPZ DNS firewall records will be

|name|type|content|
|----|----|-------|
|adtlgc.com.rpz.mypdns.cloud|CNAME|.|
|*.adtlgc.com.rpz.mypdns.cloud|CNAME|.|

**Comment by spirillen** [comment]
Closed by f2ade492e4a2c870e1d464fb734ac43c193ef028 and a9e97814ca0a3eea3d4ef0a7f468fe2078ab74bc
