### ISSUE TITLE
mmstat.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#22]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
mmstat.com   CNAME . ; Tracking
*.mmstat.com   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

<details><Summary>RPZ History</summary>

```
gds.mmstat.com.rpz.mypdns.cloud
mmstat.com.rpz.mypdns.cloud
aligtr010.mmstat.com.rpz.mypdns.cloud
aligtr020.mmstat.com.rpz.mypdns.cloud
aligtr030.mmstat.com.rpz.mypdns.cloud
aligtr050.mmstat.com.rpz.mypdns.cloud
aligtr060.mmstat.com.rpz.mypdns.cloud
aligtr070.mmstat.com.rpz.mypdns.cloud
aligtr080.mmstat.com.rpz.mypdns.cloud
aligtr001.mmstat.com.rpz.mypdns.cloud
aligtr011.mmstat.com.rpz.mypdns.cloud
aligtr021.mmstat.com.rpz.mypdns.cloud
aligtr031.mmstat.com.rpz.mypdns.cloud
aligtr051.mmstat.com.rpz.mypdns.cloud
aligtr061.mmstat.com.rpz.mypdns.cloud
aligtr071.mmstat.com.rpz.mypdns.cloud
aligtr081.mmstat.com.rpz.mypdns.cloud
yt1.mmstat.com.rpz.mypdns.cloud
aligtr002.mmstat.com.rpz.mypdns.cloud
aligtr012.mmstat.com.rpz.mypdns.cloud
aligtr032.mmstat.com.rpz.mypdns.cloud
aligtr042.mmstat.com.rpz.mypdns.cloud
aligtr052.mmstat.com.rpz.mypdns.cloud
aligtr062.mmstat.com.rpz.mypdns.cloud
aligtr072.mmstat.com.rpz.mypdns.cloud
aligtr082.mmstat.com.rpz.mypdns.cloud
yt2.mmstat.com.rpz.mypdns.cloud
aligtr003.mmstat.com.rpz.mypdns.cloud
aligtr013.mmstat.com.rpz.mypdns.cloud
aligtr023.mmstat.com.rpz.mypdns.cloud
aligtr033.mmstat.com.rpz.mypdns.cloud
aligtr043.mmstat.com.rpz.mypdns.cloud
aligtr053.mmstat.com.rpz.mypdns.cloud
aligtr063.mmstat.com.rpz.mypdns.cloud
aligtr073.mmstat.com.rpz.mypdns.cloud
aligtr083.mmstat.com.rpz.mypdns.cloud
aligtr004.mmstat.com.rpz.mypdns.cloud
aligtr014.mmstat.com.rpz.mypdns.cloud
aligtr024.mmstat.com.rpz.mypdns.cloud
aligtr034.mmstat.com.rpz.mypdns.cloud
aligtr044.mmstat.com.rpz.mypdns.cloud
aligtr064.mmstat.com.rpz.mypdns.cloud
aligtr074.mmstat.com.rpz.mypdns.cloud
aligtr084.mmstat.com.rpz.mypdns.cloud
aligtr005.mmstat.com.rpz.mypdns.cloud
aligtr015.mmstat.com.rpz.mypdns.cloud
aligtr025.mmstat.com.rpz.mypdns.cloud
aligtr035.mmstat.com.rpz.mypdns.cloud
aligtr045.mmstat.com.rpz.mypdns.cloud
aligtr055.mmstat.com.rpz.mypdns.cloud
aligtr075.mmstat.com.rpz.mypdns.cloud
aligtr006.mmstat.com.rpz.mypdns.cloud
aligtr016.mmstat.com.rpz.mypdns.cloud
aligtr026.mmstat.com.rpz.mypdns.cloud
aligtr036.mmstat.com.rpz.mypdns.cloud
aligtr046.mmstat.com.rpz.mypdns.cloud
aligtr066.mmstat.com.rpz.mypdns.cloud
aligtr076.mmstat.com.rpz.mypdns.cloud
aligtr007.mmstat.com.rpz.mypdns.cloud
aligtr017.mmstat.com.rpz.mypdns.cloud
aligtr037.mmstat.com.rpz.mypdns.cloud
aligtr047.mmstat.com.rpz.mypdns.cloud
aligtr057.mmstat.com.rpz.mypdns.cloud
aligtr067.mmstat.com.rpz.mypdns.cloud
aligtr077.mmstat.com.rpz.mypdns.cloud
aligtr008.mmstat.com.rpz.mypdns.cloud
aligtr018.mmstat.com.rpz.mypdns.cloud
aligtr028.mmstat.com.rpz.mypdns.cloud
aligtr038.mmstat.com.rpz.mypdns.cloud
aligtr048.mmstat.com.rpz.mypdns.cloud
aligtr058.mmstat.com.rpz.mypdns.cloud
aligtr009.mmstat.com.rpz.mypdns.cloud
aligtr019.mmstat.com.rpz.mypdns.cloud
aligtr029.mmstat.com.rpz.mypdns.cloud
aligtr039.mmstat.com.rpz.mypdns.cloud
aligtr049.mmstat.com.rpz.mypdns.cloud
aligtr059.mmstat.com.rpz.mypdns.cloud
ga.mmstat.com.rpz.mypdns.cloud
gxb.mmstat.com.rpz.mypdns.cloud
ac.mmstat.com.rpz.mypdns.cloud
hd.mmstat.com.rpz.mypdns.cloud
oneid.mmstat.com.rpz.mypdns.cloud
perf.mmstat.com.rpz.mypdns.cloud
log.mmstat.com.rpz.mypdns.cloud
sg.mmstat.com.rpz.mypdns.cloud
gj.mmstat.com.rpz.mypdns.cloud
gm.mmstat.com.rpz.mypdns.cloud
wgm.mmstat.com.rpz.mypdns.cloud
go.mmstat.com.rpz.mypdns.cloud
wgo.mmstat.com.rpz.mypdns.cloud
p3p.mmstat.com.rpz.mypdns.cloud
log.gds.mmstat.com.rpz.mypdns.cloud
gj.gds.mmstat.com.rpz.mypdns.cloud
gm.gds.mmstat.com.rpz.mypdns.cloud
res.mmstat.com.rpz.mypdns.cloud
ws.mmstat.com.rpz.mypdns.cloud
yt.mmstat.com.rpz.mypdns.cloud
ju.mmstat.com.rpz.mypdns.cloud
www.mmstat.com.rpz.mypdns.cloud
dz.mmstat.com.rpz.mypdns.cloud
hz.mmstat.com.rpz.mypdns.cloud
cnzz.mmstat.com.rpz.mypdns.cloud
```

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
