### ISSUE TITLE
aliyuncs.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#23]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
aliyuncs.com   CNAME . ; Tracking
*.aliyuncs.com   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +15 | \|\|aliyuncs.com/r.png? | -- | `www.aliexpress.com` | 3 | xhr | `https://retcode-us-west-1.arms.aliyuncs.com/r.png?t=pv&times=1&page=en_USHomePage&tag=&release=&environment=production&begin=1578696386117&uid=56k6j5j68q5rLF2IRbC1czwyRU6L&dt=AliExpress%20-%20Online%20Shopping%20for%20Popular%20Electronics%2C%20Fashion%2C%20Home%20%26%20Garden%2C%20Toys%20%26%20Sports%2C%20Automobiles%20and%20More.&dl=https%3A%2F%2Fwww.aliexpress.com%2F&dr=&dpr=1.00&de=utf-8&ul=&sr=1366x768&vp=1180x559&ct=&pid=f1fxt4k42w%40603c0c54f7887fb&_v=1.8.3&sid=Cykka5mX8d0rya2ybbk1036zybak&sampling=1&z=k58r2b0z` |
| +15 | \|\|aliyuncs.com/r.png? | -- | `www.aliexpress.com` | 3 | xhr | `https://retcode-us-west-1.arms.aliyuncs.com/r.png?t=resourceError&times=1&page=en_USHomePage&tag=&release=&environment=production&begin=1578696385251&src=https%3A%2F%2Fmessage.aliexpress.com%2Fmessage%2FmessageUnreadCountAjaxService.htm%3F_%3D1578696384201&node_name=script&xpath=html%20%3E%20head%20%3E%20script&sr=1366x768&vp=1180x559&ct=&uid=56k6j5j68q5rLF2IRbC1czwyRU6L&pid=f1fxt4k42w%40603c0c54f7887fb&_v=1.8.3&sid=Cykka5mX8d0rya2ybbk1036zybak&sampling=1&z=k58r2b0y` |
| +15 | \|\|aliyuncs.com/r.png? | -- | `www.aliexpress.com` | 3 | xhr | `https://retcode-us-west-1.arms.aliyuncs.com/r.png?t=resourceError&times=1&page=en_USHomePage&tag=&release=&environment=production&begin=1578696380708&src=https%3A%2F%2Fus.ynuf.aliapp.org%2Fw%2Fcb.js&node_name=script&xpath=html%20%3E%20head%20%3E%20script&sr=1366x768&vp=1180x559&ct=&uid=56k6j5j68q5rLF2IRbC1czwyRU6L&pid=f1fxt4k42w%40603c0c54f7887fb&_v=1.8.3&sid=Cykka5mX8d0rya2ybbk1036zybak&sampling=1&z=k58r2b0x` |
| +15 | \|\|aliyuncs.com/r.png? | -- | `www.aliexpress.com` | 3 | xhr | `https://retcode-us-west-1.arms.aliyuncs.com/r.png?t=resourceError&times=1&page=en_USHomePage&tag=&release=&environment=production&begin=1578696380673&src=https%3A%2F%2Fgj.mmstat.com%2Feg.js&node_name=script&xpath=html%20%3E%20head%20%3E%20script&sr=1366x768&vp=1180x559&ct=&uid=56k6j5j68q5rLF2IRbC1czwyRU6L&pid=f1fxt4k42w%40603c0c54f7887fb&_v=1.8.3&sid=Cykka5mX8d0rya2ybbk1036zybak&sampling=1&z=k58r2b0w` |
</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
