### ISSUE TITLE
mpulse.net

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#24]
## Summary

This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
mpulse.net   CNAME . ; DomainSharks
*.mpulse.net   CNAME . ; DomainSharks
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72193326-319dda00-3409-11ea-81a2-5e753d54e88a.png)

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [ ] Checked the internet for verification?
- [ ] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [ ] Added to Source file
