### ISSUE TITLE
mpulse.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#25]
## Summary

This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
mpulse.com   CNAME . ; DomainSharks
*.mpulse.com   CNAME . ; DomainSharks
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72193355-542ff300-3409-11ea-9f29-248a34df7394.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file

**Comment by spirillen** [comment]
Closed with 99b83a56c41234e8f099db95ec5057d9b9999653
