### ISSUE TITLE
bravosweet.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#266]
## Summary
This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
bravosweet.com   CNAME . ; DomainSharks
*.bravosweet.com   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
```
whois bravosweet.com
   Domain Name: BRAVOSWEET.COM
   Registry Domain ID: 2281121242_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namebright.com
   Registrar URL: http://www.DropCatch1186.com
   Updated Date: 2020-01-25T14:01:42Z
   Creation Date: 2018-06-30T18:49:18Z
   Registry Expiry Date: 2020-06-30T18:49:18Z
   Registrar: DropCatch.com 1186 LLC
   Registrar IANA ID: 3395
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS1.PARKLOGIC.COM
   Name Server: NS2.PARKLOGIC.COM
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74220654-6aeb9300-4cb0-11ea-86f0-b9ffcd1d9125.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [X] Added to Source file
