### ISSUE TITLE
bushesbint.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#267]
## Summary
This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
bushesbint.com   CNAME . ; DomainSharks
*.bushesbint.com   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
```
whois bushesbint.com
   Domain Name: BUSHESBINT.COM
   Registry Domain ID: 1256524335_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.fabulous.com
   Registrar URL: http://www.fabulous.com
   Updated Date: 2019-08-14T14:02:39Z
   Creation Date: 2007-10-05T10:24:45Z
   Registry Expiry Date: 2020-10-05T10:24:45Z
   Registrar: Sea Wasp, LLC
   Registrar IANA ID: 411
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
   Name Server: NS1.ABOVE.COM
   Name Server: NS2.ABOVE.COM
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | /glp?r=*&rw=*&rh=*&ww=*&wh=$script,1p | -- | ww25.bushesbint.com | 1 | script | `http://ww25.bushesbint.com/glp?r=http%3A%2F%2Fww25.bushesbint.com%2F&u=http%3A%2F%2Fww25.bushesbint.com%2F&z&rw=1366&rh=768&ww=1178&wh=559` |
| +2 |  |  | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/favicon.ico` |
| +2 | /px.gif? | -- | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/px.gif?ch=2&rn=1.931464221932616` |
| +2 | /px.gif? | -- | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/px.gif?ch=1&rn=1.931464221932616` |
| +2 | \|\|google.*^ | -- | ww25.bushesbint.com | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +2 |  |  | ww25.bushesbint.com | 1 | doc | `http://ww25.bushesbint.com/?z` |
| +2 |  |  | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/favicon.ico` |
| +2 | /px.gif? | -- | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/px.gif?ch=2&rn=7.497999053586905` |
| +2 | /px.gif? | -- | ww25.bushesbint.com | 1 | image | `http://ww25.bushesbint.com/px.gif?ch=1&rn=7.497999053586905` |
| +2 | \|\|google.*^ | -- | ww25.bushesbint.com | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +1 |  |  | ww25.bushesbint.com | 1 | doc | `http://ww25.bushesbint.com/` |
| +0 |  |  | bushesbint.com | 1 | doc | `http://bushesbint.com/` |
</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
