### ISSUE TITLE
faymobi.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#27]
## Summary

This fucked up 'Spyware' domain have to be blocked as..

- [ ] [Single Domain](source/spyware/domains.list)
- [X] [Wild carded](source/spyware/wildcard.list)

```python
faymobi.com   CNAME . ; SpyWare
*.faymobi.com   CNAME . ; SpyWare
```

... ***because***:

## Relevant logs and/or screenshots

The following is a complete rip-off from https://www.evina.fr/a-malware-rises-to-the-top-applications-in-google-play-store/ as the information is rather savir to infected users

# Evina found a malware in the Google Play Store’s top application rankings called “Stars Wallpapers.”

This malware is able to simulate real human behavior and take several actions like clicking on ad banners or subscribe to paying services. It is also able to activate/deactivate wifi and send/read SMS on the device.

Users complaint on the app Play Store page: content was disappointing, and some users have been subscribed to paid services without their consent. We also were able to confirm that EVINA DCBprotect blocked this malware since its very beginning. Companies protected by our solution have not been impacted by this fraud.

Since last weekend the application is ranked in the top free applications in France, Germany, Italy, Spain and in the Netherlands.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/045ef0fa21ddee4cb4e248b12c0a0d55/image.png)

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/87a7d088e1306d785b863f01b96b2a66/image.png)  
Google Play Store Ranking (Source AppBrain)

“Stars Wallpapers” has been downloaded more than 100,000 times in three days between January 2nd and January 5th.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/79b6ed428e677ac27592dc46febdadeb/image.png)  
Number of installations (Source AppBrain)

## How did we find it?
Evina uses its own global proxies network to catch frauds. We noticed an unusual behavior of few of them (data consumption higher than expected, bill invoiced for premium service). When noticing this kind of behavior, we dug on history and found where it came from: an application called “Stars Wallpapers.”

During the application’s analysis, we spotted that a piece of code of the application was missing even though it was declared.

We quickly realized that a library inside the application loads the fraudulent code. It creates two encrypted Dex files and deletes one of them as soon as it has been created and then loads it into the memory.

This method prevents detection by Google Play Store because the malicious code is not directly in the application.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/b1193fa6b6f37a2efd1b19c0cc2fa634/image.png)
The application loads the library at start

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/0f8d7886532b39d6a3c78cdd067a618a/image.png)
Stack view of libkf.so library

First of all, the malware creates an invisible window to track the user’s behavior and trigger the fraud at the right time.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/a2407d77c3f507532ddce16eb73b194e/image.png)  
Sample code of Stars Wallpapers malware

During this time, the application receives and writes instructions in streaming with a server on the faymobi.com domain on port 9091 (which helps to hide these exchanges).

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/f001df467ab19890fc8ca2ba5a4e8483/image.png)

Fraud instructions are stored in the application’s shared preferences. It contains encrypted information about the javascript actions to execute but also the information whether you have to send a sms or if you have to pass a captcha during the journey.

It also includes the time interval between each attack and the maximum number of attacks per day.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/dab2fa5de051964b946c97b82602bf03/image.png)  
Encrypted fraud instructions in shared_prefs folder

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/f59db59ea35a411e85a04de020eaab5c/image.png)  
Scan the captcha and send to an API to get the result

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/3d6d0796f20f2fa81ef0edac9f11ce77/image.png)  
Check to see if a new SMS is received

At the right time, the malware disables the wifi to be on the mobile network and launches an invisible browser, it executes all the actions of the file in the shared_prefs which thus subscribes to a premium service.

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/41db7b3de7006bec6992fd3c999ec6fd/image.png)  
Disable wifi

![image](https://gitlab.com/my-privacy-dns/matrix/matrix/uploads/3f3e15ccc1c0683c04528dbce8b12845/image.png)  
Launch Webview

It is common to say that malware hides in unofficial store or is not very visible and contains suspicious permissions.

That’s why Stars Wallpapers is dangerous because it doesn’t ask for any suspicious permissions, the content of the application looks professional and above all it is very well-ranked on Google Play Store.

Fortunately, victims of this malware were able to comment or rate this application to warn of its dangerousness, which stopped its number of installations but not its ranking.

It is therefore necessary to be careful with the applications you download, to limit the risk we advise you:
  * To check the comments on the application page
  * To check the permissions (a wallpaper app don’t need to have phone permissions)

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
