### ISSUE TITLE
zap.buzz

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#278]
## Summary

It's a plain 'Redirector' that have to be blocked as..

- [ ] [Single Domain](source/redirector/domains.list)
- [X] [Wild carded](source/redirector/wildcard.list)

```python
zap.buzz   CNAME . ; ReDirector, Tracking
*.zap.buzz   CNAME . ; ReDirector, Tracking
```

## Relevant logs and/or screenshots

```
Link management: Short-links are key to generating heavy traffic. Effortlessly monitor your custom branded URLs to gain tremendous exposure.

Analytics: Our in-depth and comprehensive analytics allow you to see what works in real-time. You can track clicks coming from various devices to grasp the bigger picture of your campaign.
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74476748-4d821900-4eaa-11ea-84a6-914b9e4fbe0e.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
