### ISSUE TITLE
sendyourpush.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#288]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
sendyourpush.com   CNAME . ; AdWare
*.sendyourpush.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

<https://github.com/easylist/easylist/pull/4890>

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74484736-7362ea00-4eb9-11ea-9362-72c1de0fc551.png)

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [ ] Checked the internet for verification?
- [ ] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
