### ISSUE TITLE
exelator.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#293]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
exelator.com   CNAME . ; AdWare
*.exelator.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

This domain redirects to `https://www.nielsen.com/us/en/solutions/capabilities/nielsen-marketing-cloud/` and was provided by @jawz101 in https://github.com/mypdns/matrix/issues/279#issuecomment-586011071

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/74487467-d6f01600-4ebf-11ea-8133-6592af8e63a0.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
