### ISSUE TITLE
adsxgm.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#296]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
adsxgm.com   CNAME . ; AdWare
*.adsxgm.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots
Found this at <https://github.com/easylist/easylist/pull/4883> and from `dig axfr rpz.mypdns.cloud`

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/74489731-7dd7b080-4ec6-11ea-9f69-9751261d7655.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [X] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
