### ISSUE TITLE
adtag.cc

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#299]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
adtag.cc   CNAME . ; AdWare
*.adtag.cc   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

<https://github.com/easylist/easylist/pull/4883/files#diff-4903e7590de76df1abe1703921a2c88bR727>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [X] RPZ Server (Team @Spirillen)
- [X] Added to Source file
