### ISSUE TITLE
360totalsecurity.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#3]
## Summary

This fucked up 'Spyware' domain have to be blocked as..

- [ ] [Single Domain](source/spyware/domains.list)
- [X] [Wild carded](source/spyware/wildcard.list)

```python
360totalsecurity.com   CNAME . ; SpyWare
*.360totalsecurity.com   CNAME . ; SpyWare
```

... ***because***:

## Relevant logs and/or screenshots

Import from http://wiki.mypdns.org/ticket/63

 While searching for an alternative free AntiVirus software to Avast we came across some Chinese Software called 360 Total Security

A couple of red light of cursed turned clear red as it's Chinese, which by default is a country you should have a good disbelieve to when it comes to secure software. China is the number 1 hacking country in the world, and unfortunately for the people, the only country which is completely blocked from any of our services.

Next we did start a search about others experiences, host files etc to see if there could be any reason for the clear red warning light that turned up before.

on ​pcfixhelp.net we found this:

Technically, 360 Total Security is not a virus, but however it has skill to place its folders, files and registry keys deeply into the operating system. Sometimes, it's very hard to delete it completely. Also, this software monitors your actions, while you are browsing Amazon, e-bay and other websites like these. It differs the site type and attempts to grasp what special offers or coupons are available to demonstrate at the present time. Furthermore, 360 Total Security either successfully employs the wide set of spying technologies: web beacons, cookies, etc., in order to clear your browsing manners and provide you advertisements that are the most relevant to your favors. Above all, 360 Total Security congregates the data about search terms, your behavior on the Internet, pages you visit and clicks you make. Some experts say that 360 Total Security uses its wide client base to make some marketing researches, or even uses the personal information of its customers to earn money. if you are tired of all this stuff, and of all ads that Total Security shows you - you can easily remove it with help of our instructions

Not that i would endorse this site, but they tent to find some good stuff and have knowledge of their topics, and clearly this quote says we need to do some more digging on this domain and software.

If ​http://pcfixhelp.net are right about 360 Total Security, then the software is no less than SpyWare, TrackWare and MalWare and that very very bad

By installing the 360totalsecurity we also got the SpyWare-, AdWare- tracker from Ciuvo installed as other have described in ticket:75. So far we only seen that Ciuvo hijacking our FireFox browser where the hack calls it-self for every sites we are visiting.

This is far from what should be expected from a security program.....

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file

/label ~Spyware  
/assign @AnonymousPoster @Spirillen
/estimate 15m
/weight 9
