### ISSUE TITLE
yomeno.xyz

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#300]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
yomeno.xyz   CNAME . ; AdWare
*.yomeno.xyz   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

https://github.com/easylist/easylist/pull/4911
## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74495034-ecbd0580-4ed6-11ea-915d-15a638be84c0.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
