### ISSUE TITLE
ymads.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#302]
## Summary

This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
ymads.com   CNAME . ; DomainSharks
*.ymads.com   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
This domain get redirected to `https://www.domainmarket.com/buynow/ymads.com?__cf_chl_jschl_tk__=6a19352325cde9a5c3e71913ca42ee7553a01d45-1581646315-0-ARBAJgJJiK4nDXPwpKPA7chw8ypRHsh1f4aUtJ3r2Y5GXNVeI8TAiIWJ96WnhiPmrGqczgc7JPwt7a1TQmTnC2hvlnEfFkJVruglatHOGi8ET1R5Ho6xFBcjgQRDFg4mlMtKFWNZ_YT_orl6KpJMcFoiNbhZYdi7GDjYiX66SpZEQ6u38TX_kpdlrHgijuNLtFlpnITLb1QvEvfGT7VwBPxCx1yezYW1ig6XE0DNw4eIjStnP5sQkqEpP49Gc7WeASzTz1J6WyXVNrQ-o-wilxV1IwF0ElhC544W2VQMhaUnI6BDj_NbP85Ei94EmIKerz2nbBjgaZlOdeIL77zJhQqcNbUDQqXoQY64lZTybKCY`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 |  |  | `www.domainmarket.com` | 1 | image | `https://www.domainmarket.com/favicon.ico` |
| +1 | \|\|facebook.net^$script | -- | `www.domainmarket.com` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | image | `https://cdn.domainmarket.com/images/accurate-appraisals.png` |
| +1 | \|\|googleadservices.com^$3p | -- | `www.domainmarket.com` | 3 | script | `https://www.googleadservices.com/pagead/conversion.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | image | `https://cdn.domainmarket.com/images/make-millions-book.png` |
| +1 |  |  | `www.domainmarket.com` | 1 | image | `https://cdn.domainmarket.com/images/excel_icon.gif` |
| +1 |  |  | `www.domainmarket.com` | 1 | image | `https://cdn.domainmarket.com/images/tracy-fogarty.jpg` |
| +1 | \|\|cdn.livechatinc.com/tracking.js | -- | `www.domainmarket.com` | 3 | script | `https://cdn.livechatinc.com/tracking.js` |
| +1 | \|\|pingdom.net^$3p | -- | `www.domainmarket.com` | 3 | script | `https://rum-static.pingdom.net/prum.min.js` |
| +1 | google-analytics.com/analytics.js | << | `www.domainmarket.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | `www.domainmarket.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|googleapis.com^$important | -- | `www.domainmarket.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900` |
| +1 | googletagmanager.com/gtm.js | << | `www.domainmarket.com` |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KHRNW38` |
| +1 | \|\|googletagmanager.com/gtm.js$script | -- | `www.domainmarket.com` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KHRNW38` |
| +1 | \|\|googleadservices.com^$3p | -- | `www.domainmarket.com` | 3 | script | `https://www.googleadservices.com/pagead/conversion.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://cdn.domainmarket.com/js/app.js?v=` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://cdn.domainmarket.com/js/lander.js?v=` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://cdn.domainmarket.com/js/inview.min.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://cdn.domainmarket.com/js/jquery.waypoints.min.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://www.domainmarket.com/js/landers/numberTickerLander.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | script | `https://www.domainmarket.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js` |
| +1 |  |  | `www.domainmarket.com` | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js` |
| +1 |  |  | `www.domainmarket.com` | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js` |
| +1 |  |  | `www.domainmarket.com` | 1 | css | `https://cdn.domainmarket.com/css/app.css?v=` |
| +1 |  |  | `www.domainmarket.com` | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css` |
| +1 | \|\|googleapis.com^$important | -- | `www.domainmarket.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext` |
| +0 |  |  | `www.domainmarket.com` | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css` |
| +0 |  |  | `www.domainmarket.com` | 1 | doc | `https://www.domainmarket.com/buynow/ymads.com` |
| +0 |  |  | ymads.com | 1 | doc | `http://ymads.com/` |
</details>

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74495610-8cc75e80-4ed8-11ea-8c1c-2cfb24138869.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
