### ISSUE TITLE
yottacash.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#304]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
yottacash.com   CNAME . ; AdWare
*.yottacash.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

This domain looks suspiciously like it is hijacked, but it is listed as adserver in [EasyList](https://github.com/easylist/easylist/pull/4911/files#diff-4903e7590de76df1abe1703921a2c88bR5492)

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | /glp?r=*&rw=*&rh=*&ww=*&wh=$script,1p | -- | ww6.yottacash.com | 1 | script | `http://ww6.yottacash.com/glp?r=http%3A%2F%2Fww6.yottacash.com%2F&u=http%3A%2F%2Fww6.yottacash.com%2F&z&rw=1366&rh=768&ww=1178&wh=559` |
| +1 |  |  | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/favicon.ico` |
| +1 | /px.gif? | -- | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/px.gif?ch=2&rn=3.7391355825340034` |
| +1 | /px.gif? | -- | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/px.gif?ch=1&rn=3.7391355825340034` |
| +1 | \|\|google.*^ | -- | ww6.yottacash.com | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +1 |  |  | ww6.yottacash.com | 1 | doc | `http://ww6.yottacash.com/?z` |
| +1 |  |  | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/favicon.ico` |
| +1 | /px.gif? | -- | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/px.gif?ch=2&rn=2.7148319306616715` |
| +1 | /px.gif? | -- | ww6.yottacash.com | 1 | image | `http://ww6.yottacash.com/px.gif?ch=1&rn=2.7148319306616715` |
| +1 | \|\|google.*^ | -- | ww6.yottacash.com | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +1 |  |  | ww6.yottacash.com | 1 | doc | `http://ww6.yottacash.com/` |
| +1 |  |  | yottacash.com | 1 | image | `http://yottacash.com/favicon.ico` |
| +0 |  |  | yottacash.com | 1 | doc | `http://yottacash.com/` |
</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [X] RPZ Server (Team @Spirillen)
- [X] Added to Source file
