### ISSUE TITLE
youlouk.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#306]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
youlouk.com   CNAME . ; AdWare
*.youlouk.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

<https://github.com/easylist/easylist/pull/4911/files#diff-4903e7590de76df1abe1703921a2c88bR5494>

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Negative
- [x] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [x] Checked the internet for verification?
- [x] Have you successfully ran tests with your changes locally?

### Todo
- [x] RPZ Server (Team @Spirillen)
- [x] Added to Source file
