### ISSUE TITLE
youradexchange.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#307]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
youradexchange.com   CNAME . ; AdWare
*.youradexchange.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

```
c.youradexchange.com.rpz.mypdns.cloud
c2366475.c.youradexchange.com.rpz.mypdns.cloud
c35000246.c.youradexchange.com.rpz.mypdns.cloud
c11370896.c.youradexchange.com.rpz.mypdns.cloud
www.youradexchange.com.rpz.mypdns.cloud
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74496460-0a8c6980-4edb-11ea-9fc3-2609ba83c873.png)

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Negative
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [ ] Checked the internet for verification?
- [ ] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
