### ISSUE TITLE
yourlegacy.club

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#309]
## Summary

This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
yourlegacy.club   CNAME . ; DomainSharks
*.yourlegacy.club   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
```
http://www.qfind.net/?__jsfail&domain_js=yourlegacy.club&feed=Mocha&subfeed=Accepted/DesktopRow
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/74496710-cfd70100-4edb-11ea-81f4-d69907ad2a77.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
