### ISSUE TITLE
tor-project.org

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#310]
## Summary

'Typo Squatting' domain that have to be blocked as..

- [ ] [Single Domain](source/typosquatting/domains.list)
- [X] [Wild carded](source/typosquatting/wildcard.list)

```python
tor-project.org   CNAME . ; TypoSquatting
*.tor-project.org   CNAME . ; TypoSquatting
```

## Relevant logs and/or screenshots
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|sedo.cachefly.net^$domain=~sedoparking.com | -- | ww1.tor-project.org | 3 | script | `https://sedo.cachefly.net/js/jquery-1.11.3.custom.min.js` |
| +2 | \|\|sedoparking.com^$3p | -- | ww1.tor-project.org | 3 | script | `http://img.sedoparking.com/js/jquery-1.11.3.custom.min.js` |
| +2 |  |  | ww1.tor-project.org | 1 | doc | `http://ww1.tor-project.org/?sub1=88537afe-5082-11ea-848f-adc4e4edec24` |
| +0 |  |  | tor-project.org | 1 | image | `http://tor-project.org/favicon.ico` |
| +0 |  |  | tor-project.org | 1 | doc | `http://tor-project.org/?js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTU4MTg0MDQxNSwiaWF0IjoxNTgxODMzMjE1LCJpc3MiOiJKb2tlbiIsImpzIjoxLCJqdGkiOiIybnBzcHJkMzZsdGNmMWpvZnMwMGkzaTgiLCJuYmYiOjE1ODE4MzMyMTUsInRzIjoxNTgxODMzMjE1MTU0NTc5fQ.liXfh4M4QA3bkSSQY4J1ozvVjEOMj3DIIqX-zoc03nc&sid=88537afe-5082-11ea-848f-adc4e4edec24` |
| +0 |  |  | tor-project.org | 1 | doc | `http://tor-project.org/` |
</details>

## Screenshots

<details><Summary>Screenshot required</summary>

Redirected via `usd.veremund-hon.com` to `succesfulday.com`  
![image](https://user-images.githubusercontent.com/5105020/74600008-33ebf780-508b-11ea-8f1a-865e4cb14571.png)

![image](https://user-images.githubusercontent.com/5105020/74600012-42d2aa00-508b-11ea-97ed-ab1ec2ca3c0d.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members) Protected by DNS FireWalling `sedoparking` DNS servers
- [ ] Added to Source file
