### ISSUE TITLE
veremund-hon.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#311]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
veremund-hon.com   CNAME . ; AdWare
*.veremund-hon.com   CNAME . ; AdWare
```

## Relevant logs and/or screenshots

See https://github.com/mypdns/matrix/issues/310

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://user-images.githubusercontent.com/5105020/74600008-33ebf780-508b-11ea-8f1a-865e4cb14571.png)
</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file
