### ISSUE TITLE
whatsap.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#313]
## Summary

'Typo Squatting' domain that have to be blocked as..

- [ ] [Single Domain](source/typosquatting/domains.list)
- [X] [Wild carded](source/typosquatting/wildcard.list)

```python
whatsap.com   CNAME . ; TypoSquatting
*.whatsap.com   CNAME . ; TypoSquatting
```

## Relevant logs and/or screenshots

If you try to visit this Typosuatting domain you'll get redirected to `http://dprtb.com/click?data=`

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
