### ISSUE TITLE
imageblues.info

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#314]
## Summary
This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
imageblues.info   CNAME . ; DomainSharks
*.imageblues.info   CNAME . ; DomainSharks
```

## Relevant logs and/or screenshots
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 |  |  | ww5.imageblues.info | 1 | image | `http://ww5.imageblues.info/favicon.ico` |
| +0 |  |  | ww5.imageblues.info | 1 | xhr | `http://ww5.imageblues.info/ls.php` |
| +0 |  |  | ww5.imageblues.info | 1 | css | `http://ww5.imageblues.info/http://parkingcrew.net/assets/themes/cleanPeppermint_7a82f1f3/style.css` |
| +0 |  |  | ww5.imageblues.info | 1 | css | `http://ww5.imageblues.info/http://parkingcrew.net/assets/themes/assets/style.css` |
| +0 | \|\|cloudfront.net/scripts/js3caf.js | -- | ww5.imageblues.info | 3 | script | `http://d1lxhc4jvstzrp.cloudfront.net/scripts/js3caf.js` |
| +0 |  |  | ww5.imageblues.info | 3 | css | `https://d1lxhc4jvstzrp.cloudfront.net/themes/cleanPeppermint_7a82f1f3/style.css` |
| +0 |  |  | ww5.imageblues.info | 3 | css | `https://d1lxhc4jvstzrp.cloudfront.net/themes/assets/style.css` |
| +0 | \|\|cloudfront.net/scripts/js3caf.js | -- | ww5.imageblues.info | 3 | script | `http://d1lxhc4jvstzrp.cloudfront.net/scripts/js3caf.js` |
| +0 | \|\|parkingcrew.net^$3p | -- | ww5.imageblues.info | 3 | script | `http://c.parkingcrew.net/scripts/sale_form.js` |
| +0 | \|\|googleapis.com^$important | -- | ww5.imageblues.info | 3 | css | `https://fonts.googleapis.com/css?family=Poppins:300` |
| +0 |  |  | ww5.imageblues.info | 3 | css | `http://d1lxhc4jvstzrp.cloudfront.net/themes/cleanPeppermint_7a82f1f3/style.css` |
| +0 |  |  | ww5.imageblues.info | 3 | css | `http://d1lxhc4jvstzrp.cloudfront.net/themes/assets/style.css` |
| +0 | \|\|google.*^ | -- | ww5.imageblues.info | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +0 |  |  | ww5.imageblues.info | 1 | doc | `http://ww5.imageblues.info/` |
</details>

See also screenshot

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/75914292-cc88c280-5e54-11ea-8aaf-b3edaee7f8c9.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file

See also: https://www.mypdns.org/ticket/194
