### ISSUE TITLE
antonioscollegestation.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#321]
## Summary

'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
antonioscollegestation.com   CNAME . ; Scam
*.antonioscollegestation.com   CNAME . ; Scam
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77250854-ed218c80-6c4a-11ea-9de8-130a2e690022.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [ ] Added to Source file
