### ISSUE TITLE
dallasmarketingservices.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#362]
## Summary

'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
dallasmarketingservices.com   CNAME . ; Scam
*.dallasmarketingservices.com   CNAME . ; Scam
```

## Relevant logs and/or screenshots
https://gist.github.com/AnonymousPoster/c5f7ee25c7f24742d126fa61dd74a1fe

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77253472-d5ea9b00-6c5a-11ea-80f8-e748ac93d8c9.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
