### ISSUE TITLE
outdooradvertisingusa.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#372]
## Summary

'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
outdooradvertisingusa.com   CNAME . ; Scam
*.outdooradvertisingusa.com   CNAME . ; Scam
```

## Relevant logs and/or screenshots
https://gist.github.com/AnonymousPoster/c5f7ee25c7f24742d126fa61dd74a1fe

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77253842-6de98400-6c5d-11ea-81ec-b83a80171682.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
