### ISSUE TITLE
puresportsnetwork.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#389]
## Summary

'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
puresportsnetwork.com   CNAME . ; Scam
*.puresportsnetwork.com   CNAME . ; Scam
```

## Relevant logs and/or screenshots
https://gist.github.com/AnonymousPoster/c5f7ee25c7f24742d126fa61dd74a1fe

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77254860-ef441500-6c63-11ea-8dc9-e8c4456134d0.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Negative
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [ ] Added to Source file
