### ISSUE TITLE
asnapieu.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#40]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
asnapieu.com   CNAME . ; Tracking
*.asnapieu.com   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

https://docs.airship.com/api/ua/#servers

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team members)
- [ ] Added to Source file

#### See also
- http://wiki.mypdns.org/ticket/124
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1768

#### Related domains
- https://github.com/mypdns/matrix/issues/39
- https://github.com/mypdns/matrix/issues/41
