### ISSUE TITLE
side6.dk

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#403]
## Summary
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
side6.dk   CNAME . ; Adult
*.side6.dk   CNAME . ; Adult
```

### additional for hosts
```shell
www.sinful.dk
www.side6.dk
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77821298-568d1980-70e9-11ea-817f-239655c6d774.png)

</details>

## Logger output
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | side6.dk | 3 | xhr | `https://y2e2h8x2.stackpathcdn.com/` | `aliasURL=https://kit-pro.fontawesome.com/releases/v5.11.2/svgs/solid/external-link-square.svg` |
| +2 |  |  | side6.dk | 3 | xhr | `https://kit-pro.fontawesome.com/releases/v5.11.2/svgs/solid/external-link-square.svg` |
| +2 |  |  | side6.dk | 3 | xhr | `https://y2e2h8x2.stackpathcdn.com/` | `aliasURL=https://kit-pro.fontawesome.com/releases/v5.11.2/svgs/solid/cog.svg` |
| +2 |  |  | side6.dk | 3 | xhr | `https://kit-pro.fontawesome.com/releases/v5.11.2/svgs/solid/cog.svg` |
| +2 |  |  | side6.dk | 1 | image | `https://side6.dk/favicon.ico` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/2/2/22487-we-vibe-chorus-par-pink_01_q100.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/2/2/22165-sinful-10-days-of-pleasure_02_q100_1.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/1/_/1_-_dk_sex_ske_starterkit_splatter_gratisglidecreme_1.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/2/1/21323-sinful-luxury-rechargeable-remote-control-panty-vibrator-q100-7.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/2/1/21257-baseks-fjernbetjent-love-vibrator-_g-q100-03.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/d/k/dk_produktbillede_sort_3.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/1/0/10163-monogamy-testvindende-erotisk-br_tspil-q100-01.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | image | `https://www.sinful.dk/media/catalog/product/cache/2/thumbnail/50x50/9df78eab33525d08d6e5fb8d27136e95/1/4/14332-autoblow-2_-xt-blowjob-maskine-q100-02.jpg` |
| +2 |  |  | `www.sinful.dk` | 3,1 | script | `https://www.sinful.dk/spot/eb/js/mootools.js` |
| +2 |  |  | `www.sinful.dk` | 3,1 | css | `https://www.sinful.dk/spot/eb/css/style.css` |
| +2 |  |  | side6.dk | 3 | script | `https://y2e2h8x2.stackpathcdn.com/` | `aliasURL=https://kit-pro.fontawesome.com/releases/v5.11.2/js/pro.min.js` |
| +1 |  |  | side6.dk | 3 | script | `https://kit-pro.fontawesome.com/releases/v5.11.2/js/pro.min.js` |
| +1 |  |  | side6.dk | 3 | frame | `https://www.sinful.dk/spot/eb/` |
| +1 | empty | << | side6.dk |  | script | `https://acdn.adnxs.com/ast/ast.js` |
| +1 | \|\|adnxs.com^ | -- | side6.dk | 3 | script | `https://acdn.adnxs.com/ast/ast.js` |
| +1 | googletagmanager.com/gtm.js | << | side6.dk |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NT5ZJ4C` |
| +1 | \|\|googletagmanager.com/gtm.js$script | -- | side6.dk | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NT5ZJ4C` |
| +1 | \|\|consent.dk^ | -- | side6.dk | 3 | script | `https://consent.dk/sp/jppolcmp.js` |
| +1 |  |  | side6.dk | 3 | css | `https://cdn.jsdelivr.net.cdn.cloudflare.net/` | `aliasURL=https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.css` |
| +1 |  |  | side6.dk | 1 | script | `https://side6.dk/assets/main.js?version=986ba9f9b54749c5e003433067ab3c035` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988023.ece/IMAGE_ALTERNATES/relationBig_200/img_3286.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/migration_catalog/side6/article4862578.ece/IMAGE_ALTERNATES/relationBig_200/Billede-9` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7677631.ece/IMAGE_ALTERNATES/relationBig_200/IMG_4846a.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7983183.ece/IMAGE_ALTERNATES/relationBig_200/_MG_1952.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7758969.ece/IMAGE_ALTERNATES/relationBig_200/2019-08-21_1342.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7987765.ece/IMAGE_ALTERNATES/relationBig_200/IMG_8968.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988043.ece/IMAGE_ALTERNATES/relationBig_200/IMG_3659.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988058.ece/IMAGE_ALTERNATES/relationBig_200/7Z4A2730.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988082.ece/IMAGE_ALTERNATES/relationBig_200/IMG_3192.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988119.ece/IMAGE_ALTERNATES/relationBig_200/IMG_1542.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988127.ece/IMAGE_ALTERNATES/relationBig_200/img_1177.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988143.ece/IMAGE_ALTERNATES/relationBig_200/img_7202.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7759022.ece/IMAGE_ALTERNATES/relationBig_200/2019-08-21_1406.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7789467.ece/IMAGE_ALTERNATES/relationBig_200/IMG_1385a.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7982954.ece/IMAGE_ALTERNATES/relationBig_200/7Z4A2409.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7789729.ece/IMAGE_ALTERNATES/relationBig_200/IMG_2900a.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/migration_catalog/side6/article4862434.ece/IMAGE_ALTERNATES/relationBig_200/Billede-5` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7797699.ece/IMAGE_ALTERNATES/relationBig_200/IMG_7084.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7987840.ece/IMAGE_ALTERNATES/relationBig_200/img_9722.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988196.ece/IMAGE_ALTERNATES/relationBig_200/IMG_9561.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989726.ece/IMAGE_ALTERNATES/relationBig_200/img_1765.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988156.ece/IMAGE_ALTERNATES/relationBig_200/IMG_9124.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989746.ece/IMAGE_ALTERNATES/relationBig_200/IMG_7877.JPG` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7988177.ece/IMAGE_ALTERNATES/relationBig_200/img_4835.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8029813.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_250803820.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8044347.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_1249902946.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8042725.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-11_1351.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8046578.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_211212901.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040482.ece/IMAGE_ALTERNATES/relationBig_150/0157%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8034408.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_623361320.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8042704.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-11_1345.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8038952.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-09_1028.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8049854.ece/IMAGE_ALTERNATES/relationBig_150/Cover%20C%20logo.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8046631.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-13_0950.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040492.ece/IMAGE_ALTERNATES/relationBig_150/0162%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040857.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_705188416.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040504.ece/IMAGE_ALTERNATES/relationBig_150/0165%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8055275.ece/IMAGE_ALTERNATES/relationBig_150/0170%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8057283.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_1178264377.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8055295.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_425576731.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040566.ece/IMAGE_ALTERNATES/relationBig_150/0166%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8055309.ece/IMAGE_ALTERNATES/relationBig_150/shutterstock_759337885.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8061260.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-23_0921.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8061686.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-23_1321.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8040573.ece/IMAGE_ALTERNATES/relationBig_500/0168%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8061270.ece/IMAGE_ALTERNATES/relationBig_500/2020-03-23_0928.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8061317.ece/IMAGE_ALTERNATES/relationBig_500/shutterstock_772231669.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8042027.ece/IMAGE_ALTERNATES/relationBig_500/0164%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8064608.ece/IMAGE_ALTERNATES/relationBig_500/missss.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8064736.ece/IMAGE_ALTERNATES/relationBig_500/awaken%20feature%20(2).jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989714.ece/IMAGE_ALTERNATES/relationBig_200/IMG_3101.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7983016.ece/IMAGE_ALTERNATES/relationBig_200/img_0995.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989762.ece/IMAGE_ALTERNATES/relationBig_200/IMG_4168.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989776.ece/IMAGE_ALTERNATES/relationBig_200/img_2630.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989792.ece/IMAGE_ALTERNATES/relationBig_200/img_5882.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989845.ece/IMAGE_ALTERNATES/relationBig_200/img_3465.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989810.ece/IMAGE_ALTERNATES/relationBig_200/img_0175.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article7989862.ece/IMAGE_ALTERNATES/relationBig_200/7Z4A0534.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8065413.ece/IMAGE_ALTERNATES/relationBig_150/2020-03-25_1528.png` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8064750.ece/IMAGE_ALTERNATES/relationBig_150/0172%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/incoming/article8042050.ece/IMAGE_ALTERNATES/relationBig_500/0167%20Cover.jpg` |
| +1 |  |  | side6.dk | 1 | image | `https://side6.dk/assets/images/side6_HH.png` |
| +1 | empty | << | side6.dk |  | script | `https://acdn.adnxs.com/ast/ast.js` |
| +1 | \|\|adnxs.com^ | -- | side6.dk | 3 | script | `https://acdn.adnxs.com/ast/ast.js` |
| +1 | \|\|consent.dk^ | -- | side6.dk | 3 | script | `https://consent.dk/sp/jppolcmp.js` |
| +1 |  |  | side6.dk | 3 | script | `https://kit.fontawesome.com/a8b648044b.js` |
| +0 |  |  | side6.dk | 1 | css | `https://side6.dk/assets/main.css?version=986ba9f9b54749c5e003433067ab3c035` |
| +0 | \|\|googleapis.com^$important | -- | side6.dk | 3 | css | `https://fonts.googleapis.com/css?family=Merriweather:400,900\|Raleway:400,400i,600,700,700i&display=swap` |
| +0 |  |  | side6.dk | 3 | css | `https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.css` |
| +0 |  |  | side6.dk | 1 | doc | `https://side6.dk/` |
| +0 |  |  | side6.dk | 1 | doc | `http://side6.dk/` |
</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](/mypdns/matrix/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](/mypdns/matrix/pulls) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Negative

### Todo
- [ ] Added to Source file?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

See also: <https://www.mypdns.org/T478>, <https://github.com/Import-External-Sources/pornhosts/issues/180> and https://github.com/Sinfonietta/hostfiles/pull/88
