### ISSUE TITLE
eromaxxx.dk

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#404]
## Summary
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
eromaxxx.dk   CNAME . ; Adult
*.eromaxxx.dk   CNAME . ; Adult
```

### additional for hosts
```shell

www.
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/77821995-fac58f00-70ee-11ea-96c3-2f7664325ae2.png)

</details>

## Logger output
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/favicon.png` |
| +2 |  |  | eromaxxx.dk | 1 | font | `https://eromaxxx.dk/fonts/glyphicons-halflings-regular.woff2` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/ic_camera_24x24_grey.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/bg-kinky.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/bg-dansk.jpg` |
| +2 | \|\|googletagmanager.com/gtag/$3p | -- | eromaxxx.dk | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-184676-22` |
| +2 | \|\|onesignal.com^$3p | -- | eromaxxx.dk | 3 | script | `https://cdn.onesignal.com/sdks/OneSignalSDK.js` |
| +2 |  |  | eromaxxx.dk | 3 | script | `https://cds.j3z9t3p6.hwcdn.net/` | `aliasURL=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/bt_nej.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/bt_ja.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/over18-girl.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/13049/300x420_677%20Michelle%20&%20Samson%20033.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/12854/300x420_Natasha_Netkjole3554.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/13033/300x420_Ella_Blue_Spandex6777.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/12877/300x420_DNP0070_125_web.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/5036/300x420_mm1045-073.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/2908/300x420_BB0192-013.JPG` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/4986/300x420_nd0126-0128.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/galleries/13034/300x420_Elise_Carwash6013.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20191/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/2252/210x293_2252.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/4497/210x293_4497.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/19000/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21069/210x293_21069.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_8.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/3416/210x293_3416.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_22.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/4641/210x293_4641.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_21.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/ic_dvd.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/cat-shortcut-world.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/cat-shortcut-scan.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/cat-shortcut-dk.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/reports/49/262x180_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/reports/50/262x180_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/reports/62/539x297_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21402/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21372/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21357/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21373/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20634/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21380/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/21381/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20591/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20679/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/18737/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/19540/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20465/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20680/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/18638/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_7.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20485/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_18.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/18816/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/eromaxxx/da/32x32_dvd_flag_28.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/ic_hd.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/films/20681/450x300_movie_main.jpg?` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/slider_signup_mobile.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/signup-anim.gif` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/243/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/242/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/245/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/231/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/250/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/thumbs/teasers/233/620x350_thumbMain.jpg` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/eromaxxx/site_logo.png` |
| +2 |  |  | eromaxxx.dk | 1 | image | `https://eromaxxx.dk/images/content/elements/girl_login.jpg` |
| +2 | \|\|googletagmanager.com/gtag/$3p | -- | eromaxxx.dk | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-184676-22` |
| +2 | \|\|onesignal.com^$3p | -- | eromaxxx.dk | 3 | script | `https://cdn.onesignal.com/sdks/OneSignalSDK.js` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/general.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.fancybox.pack.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.purl.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.tipTip.min.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.cookies.2.2.0.min.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.sbscroller.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/jquery.mousewheel.min.3.0.6.js??` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/ekko-lightbox.min.js` |
| +2 |  |  | eromaxxx.dk | 1 | css | `https://eromaxxx.dk/stylesheets/ekko-lightbox-dark.min.css` |
| +2 |  |  | eromaxxx.dk | 1 | css | `https://eromaxxx.dk/stylesheets/ekko-lightbox.min.css` |
| +2 |  |  | eromaxxx.dk | 1 | script | `https://eromaxxx.dk/javascripts/ie10-viewport-bug-workaround.min.js` |
| +2 |  |  | eromaxxx.dk | 3 | script | `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js` |
| +2 |  |  | eromaxxx.dk | 1 | css | `https://eromaxxx.dk/stylesheets/partner.css?1585394470` |
| +2 |  |  | eromaxxx.dk | 1 | css | `https://eromaxxx.dk/stylesheets/frontend.css?v2` |
| +2 |  |  | eromaxxx.dk | 1 | css | `https://eromaxxx.dk/stylesheets/bootstrap.min.css` |
| +2 |  |  | eromaxxx.dk | 3 | script | `https://code.jquery.com/jquery-1.11.3.min.js` |
| +2 | \|\|googleapis.com^$important | -- | eromaxxx.dk | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800` |
| +0 |  |  | eromaxxx.dk | 1 | doc | `https://eromaxxx.dk/` |
| +0 |  |  | eromaxxx.dk | 1 | doc | `http://eromaxxx.dk/` |
</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](/mypdns/matrix/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](/mypdns/matrix/pulls) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Negative

### Todo
- [x] Added to Source file?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
