### ISSUE TITLE
NSFW: h-moe.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#43]
## Summary
It's a plain 'Redirector' that have to be blocked as..

- [ ] [Single Domain](source/redirector/domains.list)
- [X] [Wild carded](source/redirector/wildcard.list)

```python
h-moe.com   CNAME . ; Adult, ReDirector
*.h-moe.com   CNAME . ; Adult, ReDirector
```

## Relevant logs and/or screenshots

This domain redirects to `hentai0.com`

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72677264-c011fb80-3a9a-11ea-8990-45ecc722fd8a.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team @Spirillen)
- [X] Added to Source file

**Comment by spirillen** [comment]
## DNS lookup

```bash
hentai0.com.    172800  IN      NS      ns1.nksupport.com.
hentai0.com.    172800  IN      NS      ns2.nksupport.com.
hentai0.com.    300     IN      A       23.105.12.6
hentai0.com.    300     IN      A       23.105.12.7
hentai0.com.    300     IN      NS      ns1.nksupport.com.
hentai0.com.    300     IN      NS      ns2.nksupport.com.
```

## HTTP header

```bash
HTTP/2 200 
server: nginx/1.22.1
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
cache-control: no-cache, private
date: Mon, 06 Jan 2025 02:43:33 GMT
set-cookie: XSRF-TOKEN=eyJpdiI6ImcveUxWL0swRFkvcDVoWHBtQWF3ZUE9PSIsInZhbHVlIjoiZjZsU2hGM3VHMVhCM1NVU3dPQi9LTGI4a3JmOXVnRXJ6b2FjS1RjZmJUM2w5SHQxM0QzVm9qOSt2OENJSS9FZDN6WExiQ0ExOVZkM2JGK2syak10SWdIL0Y2M1dUSVpsWmtkVGtCVlJmc3pLSCtOS1lFRlpUSk9KK25DNWRoeGkiLCJtYWMiOiIxYjhhM2I4NDI4YTQwNGVmMjJhNWJjNGE5Nzc2Yzg2N2NjY2ExMTE0OGYxY2FlMDNhNWE4ZTBmNTA2NTJiMTQ5IiwidGFnIjoiIn0%3D; expires=Wed, 05 Feb 2025 02:43:34 GMT; Max-Age=2592000; path=/; samesite=lax
set-cookie: hentai0_session_new=eyJpdiI6InFwYUhtaG5VcWMvUERIT1VZQjVaQkE9PSIsInZhbHVlIjoiUXpvY1FYL2VRbWpORzdVSFE1bjc3ZTBzaHhKQVo3bUZoM0RFSVZweFBQUTdqY05lZ2JRYWNkU1NJQzl2akE2bEhUMWs0RHdaRjVvMG1RQnMweWFycnZqYTJsMU96U21pWVVjZXJFTUp0SnAvNDFwMlJ0dGVKa1plc0tQNHdwdGgiLCJtYWMiOiIyOGU4NzgwOTkyNzI4MjUyN2Q4MDc3ZmYxZDY0NGYwNmM0NjIzYzJmMzZmNmQ2ZWQ3YTlmNTNmMGUxYWVkOTJkIiwidGFnIjoiIn0%3D; expires=Wed, 05 Feb 2025 02:43:34 GMT; Max-Age=2592000; path=/; httponly; samesite=lax
set-cookie: recommender=eyJpdiI6IkVhUTBQR25hSy9QbHR0dXhzVys0T2c9PSIsInZhbHVlIjoiMVcrTnFGUFFIQU90dkt3MC9ZMDdNWkFsL1hCc1Jia2c0YlJ5WVg5cDAzV1VIS1VCVDRzT3pEQ3Z2TEhkUko3dSIsIm1hYyI6ImNjZjdiNjJiZWU2ZWM1Nzg5NzQ1NTg4ZTFkMDU4MDdkY2Q0Y2RjOGQzNTZiYjg0OTNhMTRkM2U2YzBkY2Y0YWIiLCJ0YWciOiIifQ%3D%3D; expires=Mon, 06 Jan 2025 02:48:33 GMT; Max-Age=299; path=/; httponly; samesite=lax
x-backend-server: web1
x-frame-options: DENY
```
