### ISSUE TITLE
NSFW: myanimeron.net

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#45]
## Summary
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
myanimeron.net   CNAME . ; Sharked
*.myanimeron.net   CNAME . ; Sharked
```

## Screenshots

<details><Summary>Screenshot required</summary>

404: Not Found
![image](https://user-images.githubusercontent.com/44526987/73309575-ca629100-4222-11ea-93a3-94d81bc52c78.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?

#### See also:
- https://github.com/Sinfonietta/hostfiles/issues/80

**Comment by spirillen** [comment]
## DNS lookup

```bash
myanimeron.net. 12882   IN      A       69.16.230.165
myanimeron.net. 172800  IN      NS      ns1.parklogic.com.
myanimeron.net. 172800  IN      NS      ns2.parklogic.com.
myanimeron.net. 172800  IN      NS      ns3.parklogic.com.
```
