### ISSUE TITLE
firebaseapp.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#46]
## Summary

This fucked up 'Spyware' domain have to be blocked as..

- [ ] [Single Domain](source/spyware/domains.list)
- [X] [Wild carded](source/spyware/wildcard.list)

```python
firebaseapp.com   CNAME . ; SpyWare, TracWare
*.firebaseapp.com   CNAME . ; SpyWare, TracWare
```

... ***because***:

## Relevant logs and/or screenshots

From a wide range of hosts sources it's clear this domain can be blocked as wildcard

<details><summary>Full list of 669 records</summary>

```text
abide-appena.firebaseapp.com
accfile-made-ce775.firebaseapp.com
accountspotwdfweefopuriuityur.firebaseapp.com
add-onman.firebaseapp.com
addme-replysm.firebaseapp.com
adobeinvoice-com.firebaseapp.com
ads-game-187f4.firebaseapp.com
affont-docin.firebaseapp.com
aftena-ocage.firebaseapp.com
agnede-mado.firebaseapp.com
allow-made.firebaseapp.com
allsumit-dependess.firebaseapp.com
alpha-baude.firebaseapp.com
alphaoo.firebaseapp.com
am-sabe.firebaseapp.com
ameringobrade.firebaseapp.com
amsade-oradgere.firebaseapp.com
and-tastefineless.firebaseapp.com
ann-myfriend.firebaseapp.com
anne-melandie.firebaseapp.com
annua-ma.firebaseapp.com
ante-marone.firebaseapp.com
april-payment.firebaseapp.com
asale-mado.firebaseapp.com
asam-auten.firebaseapp.com
asan-unes.firebaseapp.com.
aseda-bena.firebaseapp.com
asen-maron.firebaseapp.com
asen-tolane.firebaseapp.com
asenda-on.firebaseapp.com
asofen-ocune.firebaseapp.com
ason-adden.firebaseapp.com
assistancemessing.firebaseapp.com
auca-caune.firebaseapp.com
auden-knote.firebaseapp.com
aughin-madone.firebaseapp.com
aune-runte.firebaseapp.com
aunte-mada.firebaseapp.com
ausen-ocun.firebaseapp.com
ausran-goken.firebaseapp.com
autade-one.firebaseapp.com
auth-login-live.firebaseapp.com
authentingate.firebaseapp.com
b-chase-com-515be.firebaseapp.com
bame-ramede.firebaseapp.com
bani-sarma.firebaseapp.com
banos-opa.firebaseapp.com
baringmariade.firebaseapp.com
bean-cone.firebaseapp.com
begin-effard.firebaseapp.com
begin-sunmaco.firebaseapp.com
bema-add.firebaseapp.com
bemace-one.firebaseapp.com
benare-onis.firebaseapp.com
bernace-do.firebaseapp.com
bima-one.firebaseapp.com
binco-marun.firebaseapp.com
bitly-onedrive-fileshare.firebaseapp.com
blm-aute.firebaseapp.com
bnes-andyanes.firebaseapp.com
bnk-login.firebaseapp.com
bnozen-apen.firebaseapp.com
boche-ma.firebaseapp.com
boitevocaleservicesms.firebaseapp.com
boma-ren.firebaseapp.com
bome-sone.firebaseapp.com
bomen-uda.firebaseapp.com
bon260-73d95.firebaseapp.com
bone-unesta.firebaseapp.com
boxtelephone-7518e.firebaseapp.com
boxytelephone.firebaseapp.com
bramsed-arrens.firebaseapp.com
buge-fone.firebaseapp.com
bun-lome.firebaseapp.com
bunode-konese.firebaseapp.com
busen-mon.firebaseapp.com
bvocalest.firebaseapp.com
caba-no.firebaseapp.com
calem-doride.firebaseapp.com
camade-raude.firebaseapp.com
cameraneole.firebaseapp.com
cams-orindgade.firebaseapp.com
camsanimera.firebaseapp.com
cante-mado.firebaseapp.com
caque-do.firebaseapp.com
cene-mado.firebaseapp.com
cermable-do.firebaseapp.com
chama-arens.firebaseapp.com
chance47-c8c6f.firebaseapp.com
chanmad-den.firebaseapp.com
charly1-77892.firebaseapp.com
charlybase23-f3090.firebaseapp.com
checkmessagerievocalewebtel.firebaseapp.com
cia-mada.firebaseapp.com
cila-yunari.firebaseapp.com
cim-aude.firebaseapp.com
cime-add.firebaseapp.com
cionde-mauco.firebaseapp.com
clame-onera.firebaseapp.com
clappest-uping.firebaseapp.com
clone-made.firebaseapp.com
cogni-ken.firebaseapp.com
cokade-made.firebaseapp.com
cokan-mo.firebaseapp.com
coki-mote.firebaseapp.com
com-nicon.firebaseapp.com
coma-natte.firebaseapp.com
come-anda.firebaseapp.com
comebacken-ast.firebaseapp.com
con-firma.firebaseapp.com
con-mara.firebaseapp.com
con-maro.firebaseapp.com
confirmacion-de-cuenta.firebaseapp.com
connect-lign-ddr.firebaseapp.com
connectpso.firebaseapp.com
cono-uade.firebaseapp.com
consa-maro.firebaseapp.com
consad-orense.firebaseapp.com
console-auth-pli-135ff3.firebaseapp.com
cookin-add.firebaseapp.com
coqueine-domessade.firebaseapp.com
costing-merined.firebaseapp.com
counco-dora.firebaseapp.com
counsa-ma.firebaseapp.com
cpares15.firebaseapp.com
craken-do.firebaseapp.com
craken-made.firebaseapp.com
cras-meand.firebaseapp.com
creet-men.firebaseapp.com
cun-marco.firebaseapp.com
dag-mot-lan.firebaseapp.com
damne-maude.firebaseapp.com
damsane-oren.firebaseapp.com
danid-rimare.firebaseapp.com
daume-taught.firebaseapp.com
daune-mague.firebaseapp.com
dcin-osin.firebaseapp.com
dconne-mahen.firebaseapp.com
decem-mada.firebaseapp.com
decen-ma.firebaseapp.com
delta0-80e64.firebaseapp.com
den-chimbo.firebaseapp.com
dence-anedem.firebaseapp.com
dencije-od.firebaseapp.com
denesa-osa.firebaseapp.com
depende-de-la-tierra.firebaseapp.com
dfunta-ocne.firebaseapp.com
dgin-mode.firebaseapp.com
din-marre.firebaseapp.com
dkon-maro.firebaseapp.com
dmaned-ormade.firebaseapp.com
dmessageries.firebaseapp.com
dobe-nica.firebaseapp.com
doble-anna.firebaseapp.com
dochunte-made.firebaseapp.com
dofe-me-do.firebaseapp.com
dogo-lema.firebaseapp.com
doinglesting.firebaseapp.com
domaneora.firebaseapp.com
donares-on.firebaseapp.com
donmi-add.firebaseapp.com
dont-manel.firebaseapp.com
dopen-addon.firebaseapp.com
dosso-maro.firebaseapp.com
douben-once.firebaseapp.com
douned-ondad.firebaseapp.com
dren-made.firebaseapp.com
dropbox-com-view-files.firebaseapp.com
dstnationdferente.firebaseapp.com
duing-okinard.firebaseapp.com
dumas-one.firebaseapp.com
dun-hunt.firebaseapp.com
during-thas.firebaseapp.com
eagle10.firebaseapp.com
ecinclento-os.firebaseapp.com
ed-mand.firebaseapp.com
eddmess-only.firebaseapp.com
edmadon-icon.firebaseapp.com
em-batma.firebaseapp.com
em-dan.firebaseapp.com
emsane-code.firebaseapp.com
emsauge-runing.firebaseapp.com
emsi-lobo.firebaseapp.com
enconsi-madine.firebaseapp.com
engu-mate.firebaseapp.com
enso-madole.firebaseapp.com
enso-maken.firebaseapp.com
ensode-amo.firebaseapp.com
eon-macinare.firebaseapp.com
esdone-aten.firebaseapp.com
eson-masa.firebaseapp.com
eusa-lombo.firebaseapp.com
euthen-ora.firebaseapp.com
evera-mada.firebaseapp.com
ezemo-add.firebaseapp.com
f68616e67696e67666c6f27login.firebaseapp.com
facebook-1131.firebaseapp.com
facebooklogin-c12cd.firebaseapp.com
faitma-oden.firebaseapp.com
falledade.firebaseapp.com
famade-reliane.firebaseapp.com
fame-doben.firebaseapp.com
fans-abmadmane.firebaseapp.com
farmedone-apting.firebaseapp.com
faura-os.firebaseapp.com
felambe-ausa.firebaseapp.com
fema-nicole.firebaseapp.com
fene-modi.firebaseapp.com
fento-maken.firebaseapp.com
fera-lofe.firebaseapp.com
fileshare-console-auth-pli-8.firebaseapp.com
fillmaten-ad.firebaseapp.com
fmanelane.firebaseapp.com
fole-mare.firebaseapp.com
foma-ura-lote.firebaseapp.com
foresta-mod.firebaseapp.com
fought-omate.firebaseapp.com
fr-bzay.firebaseapp.com
fresh-7b92d.firebaseapp.com
gamedome-achame.firebaseapp.com
gb-oden.firebaseapp.com
gean-modena.firebaseapp.com
gestmsmions.firebaseapp.com
get-reading.firebaseapp.com
gghtread.firebaseapp.com
gin-macen.firebaseapp.com
gin-morun.firebaseapp.com
gin-una.firebaseapp.com
ginnebe-aunse.firebaseapp.com
gino-maren.firebaseapp.com
glo-webdro.firebaseapp.com
gnade-oula.firebaseapp.com
god-marine.firebaseapp.com
gode-mazen.firebaseapp.com
gom-inero.firebaseapp.com
gon-macona.firebaseapp.com
gone-madin.firebaseapp.com
gone-masen.firebaseapp.com
gone-medie.firebaseapp.com
gone-sineding.firebaseapp.com
gone-ungoate.firebaseapp.com
gonime-goga.firebaseapp.com
gou-ma.firebaseapp.com
gozam-aude.firebaseapp.com
grlgr-go888.firebaseapp.com
gun-murda.firebaseapp.com
gveywmvcqo.firebaseapp.com
happynes-seing.firebaseapp.com
hello-d4cdd.firebaseapp.com
help-microwebs.firebaseapp.com
helpdesk0-b95a7.firebaseapp.com
hen-marce.firebaseapp.com
hence-mad.firebaseapp.com
henudas-mode.firebaseapp.com
hin-macasse.firebaseapp.com
hin-one.firebaseapp.com
hol2-730bb.firebaseapp.com
home-done.firebaseapp.com
hoomattera.firebaseapp.com
hum-diffen.firebaseapp.com
hun-rade.firebaseapp.com
hundo-marcinde.firebaseapp.com
husom-asale.firebaseapp.com
hvocalesm.firebaseapp.com
ichande-goge.firebaseapp.com
identification-accountpro.firebaseapp.com
identification-internetpro.firebaseapp.com
identification-logs.firebaseapp.com
idm-aest-coxnet-coxlogin.firebaseapp.com
idm-east-coxnet-my-email.firebaseapp.com
idserverswebsite.firebaseapp.com
ifen-morline.firebaseapp.com
inco-dome.firebaseapp.com
inco-loma.firebaseapp.com
incone-mon.firebaseapp.com
increase-salary.firebaseapp.com
inde-mood.firebaseapp.com
infocallmessageriechek.firebaseapp.com
infointernetprooweb.firebaseapp.com
internetpro-websmsservice.firebaseapp.com
internetservicesms.firebaseapp.com
ioniram-don.firebaseapp.com
irmane-daune.firebaseapp.com
isbankonlinebank.firebaseapp.com
isthismate-amene.firebaseapp.com
jim-once.firebaseapp.com
jima-ceintre.firebaseapp.com
jinmoxen-add.firebaseapp.com
jione-ma.firebaseapp.com
joelle-aura.firebaseapp.com
jolema-done.firebaseapp.com
jome-tame.firebaseapp.com
jomumbe-seven.firebaseapp.com
jones-mainde.firebaseapp.com
jsbymjjkps34.firebaseapp.com
jumpi-16da3.firebaseapp.com
kabens-odene.firebaseapp.com
kan-ron.firebaseapp.com
kddhjhdjhdjhd.firebaseapp.com
kinmaton-ad.firebaseapp.com
kloues2.firebaseapp.com
komso-add.firebaseapp.com
lamarinedade.firebaseapp.com
latine-trims.firebaseapp.com
leaf-tallnessgaping.firebaseapp.com
lems-optinegape.firebaseapp.com
linbe-ocune.firebaseapp.com
linco-maden.firebaseapp.com
line-f58ea.firebaseapp.com
lnofen-add.firebaseapp.com
loca-osa.firebaseapp.com
lofete-nano.firebaseapp.com
lofon-add.firebaseapp.com
lofu-maden.firebaseapp.com
logan-pal.firebaseapp.com
login-kome.firebaseapp.com
login-mimicast-com.firebaseapp.com
logina-authn.firebaseapp.com
loginonline-com.firebaseapp.com
logning-dapene.firebaseapp.com
loma-okine.firebaseapp.com
lome-asen.firebaseapp.com
lonci-adole.firebaseapp.com
losobe-ocune.firebaseapp.com
lstan-add.firebaseapp.com
macan-da.firebaseapp.com
macasepool.firebaseapp.com
mail-sending-c4274.firebaseapp.com
maked-erade.firebaseapp.com
manime-paume.firebaseapp.com
maped-camade.firebaseapp.com
march-review.firebaseapp.com
marchan-sens.firebaseapp.com
marinedaune.firebaseapp.com
masmaunedabe.firebaseapp.com
matenaquap.firebaseapp.com
maudnede.firebaseapp.com
maurlandogonzale.firebaseapp.com
mechambe-six.firebaseapp.com
meda-one.firebaseapp.com
memov-ocalmms.firebaseapp.com
men-ona.firebaseapp.com
men-spen.firebaseapp.com
messageactionss.firebaseapp.com
messagecontactst.firebaseapp.com
messagemms-3c9a5.firebaseapp.com
messageriportailltts.firebaseapp.com
messagevocalesmms.firebaseapp.com
messagportail.firebaseapp.com
mi-dim.firebaseapp.com
mikeres-e4bca.firebaseapp.com
mikozr-2d448.firebaseapp.com
mmsmessage-988ae.firebaseapp.com
mmspro-1f1cc.firebaseapp.com
mmssms-f367d.firebaseapp.com
mnsfrpls.firebaseapp.com
mode-an.firebaseapp.com
molemoringane.firebaseapp.com
momen-once.firebaseapp.com
moncompte-0range.firebaseapp.com
moo-cone.firebaseapp.com
msgmessage-7f854.firebaseapp.com
msgportable-91a1a.firebaseapp.com
msgtelephone.firebaseapp.com
msofa-mode.firebaseapp.com
nabal-pamz.firebaseapp.com
nacen-dogme.firebaseapp.com
nacone-gamette.firebaseapp.com
nadd-men.firebaseapp.com
namermete.firebaseapp.com
namo-dane.firebaseapp.com
nba-gima.firebaseapp.com
nbemasthatilnes.firebaseapp.com
nbodem-auce.firebaseapp.com
nchabe-dinner.firebaseapp.com
nedgmatabelm.firebaseapp.com
neesa-made.firebaseapp.com
nelo-addo.firebaseapp.com
nicon-licade.firebaseapp.com
nida-me.firebaseapp.com
niim-anog.firebaseapp.com
nikon-mado.firebaseapp.com
nime-ozam.firebaseapp.com
nims-one.firebaseapp.com
nione-mo.firebaseapp.com
no-amse.firebaseapp.com
no-mace.firebaseapp.com
no-mina.firebaseapp.com
nocan-made.firebaseapp.com
nocane-cande.firebaseapp.com
nodin-kee.firebaseapp.com
nofe-odaren.firebaseapp.com
nolema-oden.firebaseapp.com
nolinto-kinda.firebaseapp.com
nomen-auda.firebaseapp.com
nomeone-uname.firebaseapp.com
non-mara.firebaseapp.com
nona-okena.firebaseapp.com
notesserviceportable.firebaseapp.com
notin-oppen.firebaseapp.com
now-thabegin00336.firebaseapp.com
nozed-uname.firebaseapp.com
nso-dam.firebaseapp.com
nuderstan-ma.firebaseapp.com
numen-ocune.firebaseapp.com
ocala-made.firebaseapp.com
ocam-nora.firebaseapp.com
ocama-die.firebaseapp.com
ocaque-domen.firebaseapp.com
ocome-do.firebaseapp.com
oda-ma.firebaseapp.com
odak-mad.firebaseapp.com
offenta-donem.firebaseapp.com
offi365sharepointapps.firebaseapp.com
ofim-ma.firebaseapp.com
oftan-oden.firebaseapp.com
ofunto-made.firebaseapp.com
ogua-marre.firebaseapp.com
ojen-done.firebaseapp.com
ojoumbe-eight.firebaseapp.com
ojoumbi-six.firebaseapp.com
ojumba-one.firebaseapp.com
oma-dno.firebaseapp.com
ome-donera.firebaseapp.com
omera-web.firebaseapp.com
ommeta-add.firebaseapp.com
omoraconda.firebaseapp.com
on-dreans.firebaseapp.com
on-mada.firebaseapp.com
on-me-ro.firebaseapp.com
onage-md.firebaseapp.com
onca-mo.firebaseapp.com
once-ma.firebaseapp.com
ondage-mone.firebaseapp.com
one-history-importan.firebaseapp.com
one-male.firebaseapp.com
one-mosu.firebaseapp.com
onedrive-auth-download.firebaseapp.com
onedrive-file.firebaseapp.com
onedrive-login-live.firebaseapp.com
onedriveauth-login.firebaseapp.com
onemanes-odene.firebaseapp.com
onen-source.firebaseapp.com
oneri-jene.firebaseapp.com
ongen-mahon.firebaseapp.com
onica-made.firebaseapp.com
onmane-dun.firebaseapp.com
ons-oken.firebaseapp.com
open-losinfe.firebaseapp.com
or-connect-uese.firebaseapp.com
orange-connectcloud.firebaseapp.com
orange-security-info.firebaseapp.com
oren-mahena.firebaseapp.com
orenso-malen.firebaseapp.com
osam-dame.firebaseapp.com
osam-tone.firebaseapp.com
osdon-made.firebaseapp.com
other-person.firebaseapp.com
otiss-mone.firebaseapp.com
ousen-mado.firebaseapp.com
pass-user-dc759.firebaseapp.com
payment-april.firebaseapp.com
payment2.firebaseapp.com
personal-natwest-com-personal.firebaseapp.com
personal.firebaseapp.com
placingothering.firebaseapp.com
plusespace-eb68b.firebaseapp.com
plusmmsp.firebaseapp.com
portablenotesservice.firebaseapp.com
portableservicenotes.firebaseapp.com
portailet-memo.firebaseapp.com
portaillsmessage.firebaseapp.com
portailmss.firebaseapp.com
portailooss.firebaseapp.com
portailppms.firebaseapp.com
portailsmessagerr.firebaseapp.com
portailsms-77d5c.firebaseapp.com
postmsg-2bb64.firebaseapp.com
postnotest.firebaseapp.com
postphonet.firebaseapp.com
preendengone-hetele.firebaseapp.com
prefa-aun.firebaseapp.com
present-add.firebaseapp.com
pro-connect3036.firebaseapp.com
profils-portails.firebaseapp.com
projen-denars.firebaseapp.com
promed-romeda.firebaseapp.com
provinghans.firebaseapp.com
qck-netn.firebaseapp.com
quade-man.firebaseapp.com
quame-ocen.firebaseapp.com
quandeda-renarde.firebaseapp.com
quck-net.firebaseapp.com
quemsa-reply.firebaseapp.com
raise-pay-56506.firebaseapp.com
reaned-sames.firebaseapp.com
recnma-do.firebaseapp.com
redirect-a84ad.firebaseapp.com
redirect-pli1-authentication.firebaseapp.com
redirect1-2203f.firebaseapp.com
redirect3-4890f.firebaseapp.com
redirectccp.firebaseapp.com
redirecting-fibak.firebaseapp.com
redirectplcc.firebaseapp.com
renen-aben.firebaseapp.com
review-salaries0.firebaseapp.com
review2-e7a6a.firebaseapp.com
review4-d15d9.firebaseapp.com
reviewpay.firebaseapp.com
rezon-lason.firebaseapp.com
righte-one.firebaseapp.com
rim-samen.firebaseapp.com
robe-onsi.firebaseapp.com
rocin-mada.firebaseapp.com
rocone-mara.firebaseapp.com
roding-ma.firebaseapp.com
rome-dobte.firebaseapp.com
romeda-unade.firebaseapp.com
romes-aune.firebaseapp.com
romes-drones.firebaseapp.com
romsad-pense.firebaseapp.com
romsi-add.firebaseapp.com
ron-barada.firebaseapp.com
rosan-upa.firebaseapp.com
sa-men.firebaseapp.com
sacha-alma.firebaseapp.com
salary-raise.firebaseapp.com
salary-resource.firebaseapp.com
salary-review5.firebaseapp.com
salary5-e6118.firebaseapp.com
salay1-3b8da.firebaseapp.com
sale-mason.firebaseapp.com
salem-oden.firebaseapp.com
sam-onaroge.firebaseapp.com
same-inrune.firebaseapp.com
samed-gemed.firebaseapp.com
samon-auda.firebaseapp.com
sample2-2f790.firebaseapp.com
sample4-f6d9f.firebaseapp.com
sample5-32c7b.firebaseapp.com
samytanoh.firebaseapp.com
sandingall.firebaseapp.com
sane-quade.firebaseapp.com
sarmande-olide.firebaseapp.com
saugen-doing.firebaseapp.com
saugnadela.firebaseapp.com
sauguo-maro.firebaseapp.com
saunbaming.firebaseapp.com
sbens-tenmadedsca.firebaseapp.com
sdinfo-magen.firebaseapp.com
seceuer7c-wellsfaergo-com.firebaseapp.com
secuweb696e67666c6f6f727.firebaseapp.com
sen-kolen.firebaseapp.com
sen-manole.firebaseapp.com
sen-marens.firebaseapp.com
sen-ome-lo.firebaseapp.com
sendalinga.firebaseapp.com
sendo-meso.firebaseapp.com
senmessf.firebaseapp.com
sentmindone.firebaseapp.com
serbe-auden.firebaseapp.com
serv-web-ligne.firebaseapp.com
servicedeportable.firebaseapp.com
servicesecuweb.firebaseapp.com
servicesecuwebsite.firebaseapp.com
set-neeme.firebaseapp.com
sfin-oked.firebaseapp.com
sfn-ause.firebaseapp.com
shoessing-derpens.firebaseapp.com
sin-gardens.firebaseapp.com
sinco-mesin.firebaseapp.com
sinne-axenne.firebaseapp.com
skema-one.firebaseapp.com
sken-lontem.firebaseapp.com
skount-madone.firebaseapp.com
slafingare.firebaseapp.com
slone-mazen.firebaseapp.com
smoned-odad.firebaseapp.com
smoten-add.firebaseapp.com
smsespacepro.firebaseapp.com
smsonlinemms.firebaseapp.com
smsorange-dd216.firebaseapp.com
smsproespace.firebaseapp.com
smstelprovocale.firebaseapp.com
smswanadoo-5d6c4.firebaseapp.com
smswanadoo.firebaseapp.com
so-din-labe.firebaseapp.com
sobanta-osila.firebaseapp.com
sobin-linsa.firebaseapp.com
sobo-ans.firebaseapp.com
soda-kenas.firebaseapp.com
sodund-megote.firebaseapp.com
sofe-firma.firebaseapp.com
sofen-odde.firebaseapp.com
sofite-lonfe.firebaseapp.com
sofunta-lame.firebaseapp.com
soje-amdo.firebaseapp.com
sole-mado.firebaseapp.com
somane-onase.firebaseapp.com
some-donia.firebaseapp.com
some-taken.firebaseapp.com
son-masenlo.firebaseapp.com
sone-domen.firebaseapp.com
song-ma.firebaseapp.com
sont-sonbe.firebaseapp.com
sontime-add.firebaseapp.com
sorenbatem.firebaseapp.com
soria-most.firebaseapp.com
soude-masi.firebaseapp.com
speed-monde.firebaseapp.com
spen-do.firebaseapp.com
spone-tame.firebaseapp.com
srinaude-ocin.firebaseapp.com
storage-db-server-sliw2.firebaseapp.com
succes-reply.firebaseapp.com
sufade-osambe.firebaseapp.com
sufan-kena.firebaseapp.com
suken-losra.firebaseapp.com
sun-kenim.firebaseapp.com
sun-mos.firebaseapp.com
sunde-machade.firebaseapp.com
sune-okena.firebaseapp.com
sunfi-ocinse.firebaseapp.com
sunge-ode.firebaseapp.com
sunta-madon.firebaseapp.com
sunu-kenu.firebaseapp.com
takeno-ame.firebaseapp.com
targobank-1f094.firebaseapp.com
targobank-32410.firebaseapp.com
telephonemsg-15d51.firebaseapp.com
telephonepost-31389.firebaseapp.com
telpostpost-6baca.firebaseapp.com
telprosms.firebaseapp.com
tiwa-d055e.firebaseapp.com
torinse-comerande.firebaseapp.com
trico-ma.firebaseapp.com
ucam-one.firebaseapp.com
udome-canne.firebaseapp.com
ugem-adone.firebaseapp.com
ughest-odun.firebaseapp.com
ugua-mare.firebaseapp.com
umessageriess.firebaseapp.com
un-osa.firebaseapp.com
unfo-madone.firebaseapp.com
uni-mada.firebaseapp.com
uni-versen.firebaseapp.com
unk-line.firebaseapp.com
unsofen-add.firebaseapp.com
until-marden.firebaseapp.com
upesten-domenide.firebaseapp.com
usan-medo.firebaseapp.com
venam-ciada.firebaseapp.com
venoms-oridade.firebaseapp.com
verification-e49bf.firebaseapp.com
verification-infos.firebaseapp.com
vermade-caped.firebaseapp.com
very-musting.firebaseapp.com
vmessgaeries.firebaseapp.com
vocaleidproorangesms.firebaseapp.com
vocalese-49363.firebaseapp.com
vocalespr.firebaseapp.com
wanadoo-116c0.firebaseapp.com
warensed-olmaded.firebaseapp.com
web6-2ec39.firebaseapp.com
website-40906.firebaseapp.com
wwmesspost.firebaseapp.com
www.fr-bzay.firebaseapp.com
www.redirecting-fibak.firebaseapp.com
xembernaude-orna.firebaseapp.com
```

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [x] Added to Source file

**Comment by AnonymousPoster** [comment]
Moved to https://www.mypdns.org/T14

**Comment by spirillen** [comment]
Moved to tracking free environment <https://www.mypdns.org/T14>

**Comment by spirillen** [comment]
`chomatruider.firebaseapp.com|phishing`

Details in https://github.com/mitchellkrogza/phishing/pull/414
