### ISSUE TITLE
callsource.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#486]
### Blacklist domain as

- [ ] Wildcard, The domain should be entirely blacklisted
- [X] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Domain records

```CSV
marketing.callsource.com|tracking
```

### Screenshots

N/A

### Links to external sources

```CSS
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#callsource
```
```


### logs from uBlock Origin

N/A
