### ISSUE TITLE
bugsnag.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#49]
## Summary
This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [X] [Single Domain](source/tracking/domains.list)
- [ ] [Wild carded](source/tracking/wildcard.list)

```python
notify.bugsnag.com   CNAME . ; Tracking
sessions.bugsnag.com   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots
https://www.mypdns.org/ticket/78

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [x] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [x] Checked the internet for verification?
- [x] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team members)
- [ ] Added to Source file
