### ISSUE TITLE
NSFW: playboy.de

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#5]
## Summary

I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
playboy.de   CNAME . ; Adult
*.playboy.de   CNAME . ; Adult
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72038536-09479b80-32a2-11ea-9c27-65d22e8b9de0.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?

**Comment by spirillen** [comment]
## DNS lookup

```bash
playboy.de.     86400   IN      NS      amit.ns.cloudflare.com.
playboy.de.     86400   IN      NS      lovisa.ns.cloudflare.com.
```
