### ISSUE TITLE
cloudesystemsecurenetworksupportprovider.online

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#50]
## Summary

'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
cloudesystemsecurenetworksupportprovider.online   CNAME . ; Scam
*.cloudesystemsecurenetworksupportprovider.online   CNAME . ; Scam
```

... ***because***:

## Relevant logs and/or screenshots

http://hosts-file.net/?s=cloudesystemsecurenetworksupportprovider.online

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [x] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [x] Checked the internet for verification?
- [x] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team members)
- [x] Added to Source file
