### ISSUE TITLE
nexooon.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#52]
## Summary
'Scamming' domain that have to be blocked as..

- [ ] [Single Domain](source/scamming/domains.list)
- [X] [Wild carded](source/scamming/wildcard.list)

```python
nexooon.com   CNAME . ; Scam
*.nexooon.com   CNAME . ; Scam
```

... ***because***:

## Relevant logs and/or screenshots

https://hosts-file.net/?s=nexooon.com

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [ ] Checked the internet for verification?
- [ ] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [ ] Added to Source file
