### ISSUE TITLE
nuance.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#556]
### Blacklist domain as

- [ ] Wildcard, The domain should be entirely blacklisted
- [X] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

Microsoft entity

### Domain records

```CSV
null
```

### Sub-Domain records

```CSV
engage.nuance.com|tracking
events.nuance.com|tracking
meeting.nuance.com|tracking
ndi.nuance.com|tracking
preference.nuance.com|tracking
solutions.nuance.com|tracking
tag-wellsfargo.nod-glb.nuance.com|tracking
```

### Hosts specific records, not used by DNS RPZ firewalls

```CSS
shop.nuance.com
```

### Screenshots

N/A

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A
