### ISSUE TITLE
visualstudio.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#559]
### Blacklist domain as

- [ ] Wildcard, The domain should be entirely blacklisted
- [X] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

Microsoft entity

### Domain records

```CSV
null
```

### Sub-Domain records

```CSV
analytics.visualstudio.com|tracking
dc-int.services.visualstudio.com|tracking
dc.services.visualstudio.com|tracking
code.visualstudio.com|whitelist
```

### Screenshots

N/A

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A
