### ISSUE TITLE
dnset.com

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#57]
## Summary
This 'Malicious' domain have to be blocked as..

- [ ] [Single Domain](source/malicious/domains.list)
- [x] [Wild carded](source/malicious/wildcard.list)

```python
dnset.com   CNAME . ; Malicious
*.dnset.com   CNAME . ; Malicious
```

... ***because***:

## Relevant logs and/or screenshots

We have found a large amount of submissions of `dnset.com` in our RPZ zone and third party ~Malicious hosts sources.

My believe is therefore we should be able to reduce the necessary entries for this second level domain to be blocked by wildcard.

## History

```
Status      Percentage   Numbers     
----------- ------------ ------------
ACTIVE      98%          175         
INACTIVE    1%           3           
INVALID     0%           0           

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝
```

<details><Summary>RPZ History</summary>

```
dnset.com.rpz.mypdns.cloud
motherxhubaea.dnset.com.rpz.mypdns.cloud
asianxhubrwa.dnset.com.rpz.mypdns.cloud
asianxhubkjb.dnset.com.rpz.mypdns.cloud
tube8vidsdob.dnset.com.rpz.mypdns.cloud
slimxxxtubeiqb.dnset.com.rpz.mypdns.cloud
slimxxxtubeftb.dnset.com.rpz.mypdns.cloud
slimxxxtubexwb.dnset.com.rpz.mypdns.cloud
analxxxclipsqxb.dnset.com.rpz.mypdns.cloud
tube8vidsjac.dnset.com.rpz.mypdns.cloud
slimxxxtubeijc.dnset.com.rpz.mypdns.cloud
asianxhubkjc.dnset.com.rpz.mypdns.cloud
asianxhubauc.dnset.com.rpz.mypdns.cloud
asianxhubcxc.dnset.com.rpz.mypdns.cloud
asianxhublxc.dnset.com.rpz.mypdns.cloud
asianxhubbcd.dnset.com.rpz.mypdns.cloud
asianxhubbhd.dnset.com.rpz.mypdns.cloud
asianxhubdod.dnset.com.rpz.mypdns.cloud
asianxhubjsd.dnset.com.rpz.mypdns.cloud
slimxxxtubeuvd.dnset.com.rpz.mypdns.cloud
tube8vidsowd.dnset.com.rpz.mypdns.cloud
slimxxxtuberfe.dnset.com.rpz.mypdns.cloud
slimxxxtubejie.dnset.com.rpz.mypdns.cloud
slimxxxtuberme.dnset.com.rpz.mypdns.cloud
motherxhubape.dnset.com.rpz.mypdns.cloud
tube8vidsyre.dnset.com.rpz.mypdns.cloud
slimxxxtubemue.dnset.com.rpz.mypdns.cloud
slimxxxtuberue.dnset.com.rpz.mypdns.cloud
slimxxxtubeqve.dnset.com.rpz.mypdns.cloud
motherxhubfwe.dnset.com.rpz.mypdns.cloud
analxxxclipskwe.dnset.com.rpz.mypdns.cloud
asianxhubixe.dnset.com.rpz.mypdns.cloud
tube8vidslmf.dnset.com.rpz.mypdns.cloud
slimxxxtubeonf.dnset.com.rpz.mypdns.cloud
asianxhubwof.dnset.com.rpz.mypdns.cloud
slimxxxtubentf.dnset.com.rpz.mypdns.cloud
asianxhubaxf.dnset.com.rpz.mypdns.cloud
motherxhubeyf.dnset.com.rpz.mypdns.cloud
tube8vidsyyf.dnset.com.rpz.mypdns.cloud
analxxxclipslfg.dnset.com.rpz.mypdns.cloud
motherxhubqig.dnset.com.rpz.mypdns.cloud
slimxxxtubeklg.dnset.com.rpz.mypdns.cloud
slimxxxtubetmg.dnset.com.rpz.mypdns.cloud
motherxhubxng.dnset.com.rpz.mypdns.cloud
asianxhubdug.dnset.com.rpz.mypdns.cloud
tube8vidssyg.dnset.com.rpz.mypdns.cloud
asianxhubuyg.dnset.com.rpz.mypdns.cloud
asianxhubmzg.dnset.com.rpz.mypdns.cloud
slimxxxtubevih.dnset.com.rpz.mypdns.cloud
analxxxclipsyjh.dnset.com.rpz.mypdns.cloud
asianxhubyoh.dnset.com.rpz.mypdns.cloud
tube8vidstrh.dnset.com.rpz.mypdns.cloud
motherxhubawh.dnset.com.rpz.mypdns.cloud
asianxhuboji.dnset.com.rpz.mypdns.cloud
motherxhubcli.dnset.com.rpz.mypdns.cloud
slimxxxtubehli.dnset.com.rpz.mypdns.cloud
tube8vidslni.dnset.com.rpz.mypdns.cloud
analxxxclipshoi.dnset.com.rpz.mypdns.cloud
asianxhubgti.dnset.com.rpz.mypdns.cloud
asianxhubhaj.dnset.com.rpz.mypdns.cloud
tube8vidsvaj.dnset.com.rpz.mypdns.cloud
motherxhubrcj.dnset.com.rpz.mypdns.cloud
slimxxxtubebej.dnset.com.rpz.mypdns.cloud
motherxhubwmj.dnset.com.rpz.mypdns.cloud
slimxxxtubeppj.dnset.com.rpz.mypdns.cloud
asianxhubttj.dnset.com.rpz.mypdns.cloud
slimxxxtubedvj.dnset.com.rpz.mypdns.cloud
motherxhubgwj.dnset.com.rpz.mypdns.cloud
asianxhubwbk.dnset.com.rpz.mypdns.cloud
asianxhubjgk.dnset.com.rpz.mypdns.cloud
motherxhubehk.dnset.com.rpz.mypdns.cloud
asianxhubphk.dnset.com.rpz.mypdns.cloud
slimxxxtubectk.dnset.com.rpz.mypdns.cloud
asianxhubcal.dnset.com.rpz.mypdns.cloud
motherxhubhfl.dnset.com.rpz.mypdns.cloud
motherxhubkhl.dnset.com.rpz.mypdns.cloud
asianxhubnkl.dnset.com.rpz.mypdns.cloud
slimxxxtubeull.dnset.com.rpz.mypdns.cloud
motherxhubkml.dnset.com.rpz.mypdns.cloud
asianxhubnwl.dnset.com.rpz.mypdns.cloud
motherxhublmm.dnset.com.rpz.mypdns.cloud
tube8vidsrom.dnset.com.rpz.mypdns.cloud
asianxhubazm.dnset.com.rpz.mypdns.cloud
asianxhubran.dnset.com.rpz.mypdns.cloud
tube8vidssan.dnset.com.rpz.mypdns.cloud
slimxxxtubeacn.dnset.com.rpz.mypdns.cloud
slimxxxtubehdn.dnset.com.rpz.mypdns.cloud
motherxhubjon.dnset.com.rpz.mypdns.cloud
promosextubemun.dnset.com.rpz.mypdns.cloud
asianxhubwvn.dnset.com.rpz.mypdns.cloud
asianxhubvco.dnset.com.rpz.mypdns.cloud
asianxhubaoo.dnset.com.rpz.mypdns.cloud
asianxhubyso.dnset.com.rpz.mypdns.cloud
analxxxclipsjvo.dnset.com.rpz.mypdns.cloud
asianxhubgbp.dnset.com.rpz.mypdns.cloud
slimxxxtubeubp.dnset.com.rpz.mypdns.cloud
slimxxxtuberep.dnset.com.rpz.mypdns.cloud
motherxhubrlp.dnset.com.rpz.mypdns.cloud
tube8vidsxpp.dnset.com.rpz.mypdns.cloud
tube8vidsvtp.dnset.com.rpz.mypdns.cloud
motherxhubyxp.dnset.com.rpz.mypdns.cloud
tube8vidsnyp.dnset.com.rpz.mypdns.cloud
asianxhubfhq.dnset.com.rpz.mypdns.cloud
tube8vidsnlq.dnset.com.rpz.mypdns.cloud
slimxxxtubebmq.dnset.com.rpz.mypdns.cloud
motherxhubvnq.dnset.com.rpz.mypdns.cloud
slimxxxtubexxq.dnset.com.rpz.mypdns.cloud
asianxhubryq.dnset.com.rpz.mypdns.cloud
tube8vidsbbr.dnset.com.rpz.mypdns.cloud
slimxxxtubeocr.dnset.com.rpz.mypdns.cloud
tube8vidsrdr.dnset.com.rpz.mypdns.cloud
asianxhubber.dnset.com.rpz.mypdns.cloud
promosextubethr.dnset.com.rpz.mypdns.cloud
slimxxxtubeqwr.dnset.com.rpz.mypdns.cloud
analxxxclipsucs.dnset.com.rpz.mypdns.cloud
tube8vidsycs.dnset.com.rpz.mypdns.cloud
slimxxxtubesrs.dnset.com.rpz.mypdns.cloud
slimxxxtubetts.dnset.com.rpz.mypdns.cloud
motherxhubhus.dnset.com.rpz.mypdns.cloud
motherxhubizs.dnset.com.rpz.mypdns.cloud
nuvidxxxlbt.dnset.com.rpz.mypdns.cloud
slimxxxtubengt.dnset.com.rpz.mypdns.cloud
motherxhubzht.dnset.com.rpz.mypdns.cloud
motherxhubfmt.dnset.com.rpz.mypdns.cloud
slimxxxtubewmt.dnset.com.rpz.mypdns.cloud
asianxhubeot.dnset.com.rpz.mypdns.cloud
motherxhubtyt.dnset.com.rpz.mypdns.cloud
tube8vidsrau.dnset.com.rpz.mypdns.cloud
asianxhubycu.dnset.com.rpz.mypdns.cloud
motherxhubqnu.dnset.com.rpz.mypdns.cloud
asianxhubsuu.dnset.com.rpz.mypdns.cloud
motherxhubgwu.dnset.com.rpz.mypdns.cloud
slimxxxtubedgv.dnset.com.rpz.mypdns.cloud
slimxxxtubexiv.dnset.com.rpz.mypdns.cloud
motherxhubovv.dnset.com.rpz.mypdns.cloud
asianxhubllw.dnset.com.rpz.mypdns.cloud
tube8vidshrw.dnset.com.rpz.mypdns.cloud
tube8vidsxmx.dnset.com.rpz.mypdns.cloud
nuvidxxxpqx.dnset.com.rpz.mypdns.cloud
asianxhubgxx.dnset.com.rpz.mypdns.cloud
tube8vidsbzx.dnset.com.rpz.mypdns.cloud
tube8vidsbhy.dnset.com.rpz.mypdns.cloud
asianxhubjpy.dnset.com.rpz.mypdns.cloud
tube8vidswsy.dnset.com.rpz.mypdns.cloud
asianxhublty.dnset.com.rpz.mypdns.cloud
tube8vidsuty.dnset.com.rpz.mypdns.cloud
motherxhubavy.dnset.com.rpz.mypdns.cloud
slimxxxtubeemz.dnset.com.rpz.mypdns.cloud
asianxhubsmz.dnset.com.rpz.mypdns.cloud
tube8vidsymz.dnset.com.rpz.mypdns.cloud
tube8vidsotz.dnset.com.rpz.mypdns.cloud
zagruz.dnset.com.rpz.mypdns.cloud
```

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [ ] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [ ] Checked the internet for verification?
- [ ] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team @Spirillen)
- [ ] Added to Source file

And of curse, trying to add this report to Gilab failed by there SpyWare
![image](https://user-images.githubusercontent.com/5105020/72882541-16817300-3d03-11ea-9631-ae4f6e1e4ce8.png)

See more about this big issue at:
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/74 and https://gitlab.com/gitlab-com/support-forum/issues/4521

See also:
https://www.mypdns.org/ticket/144#ticket

**Comment by AnonymousPoster** [comment]
Fixed in commit [source:Matrix/source/malicious/wildcard.list@9838092:285#L282 9838092]
