### ISSUE TITLE
uol.com.br

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#59]
## Summary
This 'Malicious' domain have to be blocked as..

- [X] [Single Domain](source/malicious/domains.list)
- [x] [Wild carded](source/malicious/wildcard.list)

```python
adclient-af.lp.uol.com.br   CNAME . ; Malicious
adclient-uol.lp.uol.com.br   CNAME . ; Malicious
adrequisitor-af.lp.uol.com.br   CNAME . ; Malicious
uole.ad.uol.com.br   CNAME . ; Malicious
tracker.bt.uol.com.br   CNAME . ; Malicious
download.uol.com.br   CNAME . ; Malicious
p.download.uol.com.br   CNAME . ; Malicious
folha.uol.com.br   CNAME . ; Malicious
img.uol.com.br   CNAME . ; Malicious
banners.img.uol.com.br   CNAME . ; Malicious
pubshop.img.uol.com.br   CNAME . ; Malicious
lp.uol.com.br   CNAME . ; Malicious
metrics.uol.com.br   CNAME . ; Malicious
mtv.uol.com.br   CNAME . ; Malicious
ads.mtv.uol.com.br   CNAME . ; Malicious
musica.uol.com.br   CNAME . ; Malicious
sites.uol.com.br   CNAME . ; Malicious
alissonluis-musico.sites.uol.com.br   CNAME . ; Malicious
bergmann.sites.uol.com.br   CNAME . ; Malicious
rejane.bergmann.sites.uol.com.br   CNAME . ; Malicious
ccvolpe.sites.uol.com.br   CNAME . ; Malicious
claudimarsoares.sites.uol.com.br   CNAME . ; Malicious
eustaquio-nascimento.sites.uol.com.br   CNAME . ; Malicious
francanelli.sites.uol.com.br   CNAME . ; Malicious
freitas.sites.uol.com.br   CNAME . ; Malicious
gabi.freitas.sites.uol.com.br   CNAME . ; Malicious
mbiapino.sites.uol.com.br   CNAME . ; Malicious
pr.sites.uol.com.br   CNAME . ; Malicious
pedtroneves.pr.sites.uol.com.br   CNAME . ; Malicious
transmoretti.sites.uol.com.br   CNAME . ; Malicious
xpg.uol.com.br   CNAME . ; Malicious
sandroalencar0102.xpg.uol.com.br   CNAME . ; Malicious
saverhl.xpg.uol.com.br   CNAME . ; Malicious
strinof.xpg.uol.com.br   CNAME . ; Malicious
```

... ***because***:

## Relevant logs and/or screenshots
This domain comes to us from several sources as malicious

Among the source is:
```
hphosts_emd
dg-malicious
someonewhocares
hphosts_ad_servers
malwaredomainlist
mvps
```

They can all be verified at https://gitlab.com/my-privacy-dns/external-sources/hosts-sources

## ScreenShot
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/5105020/72974935-36329d00-3dd0-11ea-8c82-7029ff65cbad.png)

</details>

## History
In our rpz.mypdns.cloud DNS firewall we find a number of old records, and a few dead ones, which have been removed by this issue :smiley: 

Thanks to [PyFunceble](https://github.com/funilrys/PyFunceble) :tada: 

<details><Summary>RPZ History</summary>

```
uol.com.br, Fixed
ad.uol.com.br, dead
bt.uol.com.br, dead
adclient-af.lp.uol.com.br
adclient-uol.lp.uol.com.br
adrequisitor-af.lp.uol.com.br
uole.ad.uol.com.br
tracker.bt.uol.com.br
download.uol.com.br
p.download.uol.com.br
folha.uol.com.br
paywall.folha.uol.com.br
img.uol.com.br
banners.img.uol.com.br
pubshop.img.uol.com.br
lp.uol.com.br
metrics.uol.com.br
mtv.uol.com.br
ads.mtv.uol.com.br
musica.uol.com.br
sites.uol.com.br
alissonluis-musico.sites.uol.com.br
bergmann.sites.uol.com.br
rejane.bergmann.sites.uol.com.br
ccvolpe.sites.uol.com.br
claudimarsoares.sites.uol.com.br
drrfilho.sites.uol.com.br
www.drrfilho.sites.uol.com.br
eustaquio-nascimento.sites.uol.com.br
francanelli.sites.uol.com.br
frantes.sites.uol.com.br
www.frantes.sites.uol.com.br
freitas.sites.uol.com.br
gabi.freitas.sites.uol.com.br
mbiapino.sites.uol.com.br
pr.sites.uol.com.br
pedtroneves.pr.sites.uol.com.br
servicoscorel.sites.uol.com.br
www.servicoscorel.sites.uol.com.br
transmoretti.sites.uol.com.br
xpg.uol.com.br
sandroalencar0102.xpg.uol.com.br
saverhl.xpg.uol.com.br
strinof.xpg.uol.com.br
```

The following domains have been turned into wildcards:
```
www.servicoscorel.sites.uol.com.br.rpz.mypdns.cloud
www.drrfilho.sites.uol.com.br.rpz.mypdns.cloud
www.frantes.sites.uol.com.br.rpz.mypdns.cloud
```

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive
- [x] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [x] Checked the internet for verification?
- [x] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team @Spirillen)
- [x] Added to Source file

**Comment by AnonymousPoster** [comment]
Fixed in e1ad170

**Comment by AnonymousPoster** [comment]
See also: https://www.mypdns.org/ticket/148
