### ISSUE TITLE
rj.gov.br

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#60]
## Summary
This 'Malicious' domain have to be blocked as..
See also: https://www.mypdns.org/ticket/149

- [X] [Single Domain](source/malicious/domains.list)
- [x] [Wild carded](source/malicious/wildcard.list)

```python
rj.gov.br   CNAME . ; Malicious
miracema.rj.gov.br   CNAME . ; Malicious
natprevi.rj.gov.br   CNAME . ; Malicious
www.natprevi.rj.gov.br   CNAME . ; Malicious
central.rj.gov.br   CNAME . ; Phishing
*.central.rj.gov.br   CNAME . ; Phishing
funarj.rj.gov.br   CNAME . ; Phishing
*.funarj.rj.gov.br   CNAME . ; Phishing
silvajardim.rj.gov.br   CNAME . ; Phishing
*.silvajardim.rj.gov.br   CNAME . ; Phishing
```

... ***because***:

## Relevant logs and/or screenshots
This domain comes to us from several sources as malicious and phishing

Among the source is:
```
hphosts_psh
dg-malicious
malwaredomainlist
```

They can all be verified at [https://gitlab.com/my-privacy-dns/external-sources/hosts-sources]

## Screenshots

```
<details><Summary>Screenshot required</summary>



</details>
```

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team @Spirillen)
- [x] Added to Source file

**Comment by AnonymousPoster** [comment]
Added in commit 9e07b68
