### ISSUE TITLE
yourzip.co

### ISSUE THREAD

**Issue by AnonymousPoster** [mypdns/matrix#64]
## Summary
This outdated domain have been Sharked and should be blocked to avoid 
scam in this format..

- [ ] [Single domain blocking](source/sharked-domains/domains.list)
- [X] [Wildcarded](source/sharked-domains/wildcard.list)

```python
yourzip.co   CNAME . ; DomainSharks, Malicious
*.yourzip.co   CNAME . ; DomainSharks, Malicious
```

## Relevant logs and/or screenshots
This hijacked domain also serves viruses according to virustotal
https://www.virustotal.com/gui/domain/yourzip.co/relations
https://www.virustotal.com/gui/url/67f7197149f17438209d8ad9ffdba90e7e74b791436e4e8abe6876ca8a85fb6b/details
https://www.virustotal.com/gui/domain/giants.yourzip.co/relations

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/5105020/72982784-29b64080-3de0-11ea-9b55-4660c7629e1f.png)

![image](https://user-images.githubusercontent.com/5105020/72982771-23c05f80-3de0-11ea-84bc-588fffa8e7d4.png)

![image](https://user-images.githubusercontent.com/5105020/72982981-9f221100-3de0-11ea-8734-e85c450ba9af.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive
- [x] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [x] Checked the internet for verification?
- [x] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team members)
- [x] Added to Source file

See also: <https://www.mypdns.org/ticket/153>

**Comment by AnonymousPoster** [comment]
Closed with be72d78
