### ISSUE TITLE
ticketswap.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#68]
## Summary
This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [X] [Single Domain](source/tracking/domains.list)
- [ ] [Wild carded](source/tracking/wildcard.list)

```python
sgmnt.ticketswap.com   CNAME . ; Tracking
```

## Relevant logs and/or screenshots
- https://www.mypdns.org/ticket/157
- https://github.com/easylist/easylist/pull/4784

## Screenshots

```
<details><Summary>Screenshot required</summary>

</details>
```

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [X] RPZ Server (Team members)
- [X] Added to Source file
