### ISSUE TITLE
ianimes.org

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#69]
## Summary
This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
ianimes.org   CNAME . ; Tracking
*.ianimes.org   CNAME . ; Tracking
```

## Relevant logs and/or screenshots
Copy of: https://www.mypdns.org/ticket/158

Initiated from @smed79 [MR](https://github.com/easylist/easylist/pull/4786)

I'm getting a clue that it should be possible to block this domain entirely

I have the impression that this domain is all about tracking and violating users privacy. See attached.

As side note, as I only sees HTTP status code 504, in the last 5 minutes, this can be a temporary error, but i doubt and I would recommend to revisit this url later for confirmation.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +127 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/404.html` |
| +127 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/favicon.ico` |
| +127 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/index.php` |
| +2 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/404.html` |
| +2 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/favicon.ico` |
| +2 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/index.php` |
| +1 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/` |
| +1 |  |  | ianimes.org | 1 | doc | `https://ianimes.org/` |
| +0 |  |  | ianimes.org | 1 | doc | `http://ianimes.org/` |
</details>

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/73055896-0a75ec80-3e8e-11ea-8952-ea44804f0e02.png)

![image](https://user-images.githubusercontent.com/44526987/73055908-119cfa80-3e8e-11ea-84a8-02d07f7cd131.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [ ] RPZ Server (Team members)
- [ ] Added to Source file
