### ISSUE TITLE
adaware.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#7]
## Summary

I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
adaware.com   CNAME . ; AdWare
*.adaware.com   CNAME . ; AdWare
```

... ***because***:

## Relevant logs and/or screenshots

https://botcrawl.com/remove-adaware-web-companion/

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [x] RPZ Server (Team @Spirillen)
- [x] Added to Source file
