### ISSUE TITLE
dnsenable.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#73]
## Summary

I believe this DNS Server needs to be blocked as..

  - [ ] [Wildcarded](source/dns-servers/wildcard.list)
  - [X] [Single DNS Server](source/dns-servers/domains.list)

```python
expired1.dnsenable.com.rpz-nsdname   CNAME . ; DNSServer
expired2.dnsenable.com.rpz-nsdname   CNAME . ; DNSServer
32.3.2.168.192.rpz-nsip   CNAME . ; DNSServer
128.57.zz.1.0.db8.2001.rpz-nsip   CNAME . ; DNSServer
```

.. ***Because***:

## Relevant logs and/or screenshots
```
whois 1001jav.xyz
Domain Name: 1001JAV.XYZ
Registry Domain ID: D56092048-CNIC
Registrar WHOIS Server: whois.isimtescil.net
Registrar URL: http://www.isimtescil.net
Updated Date: 2020-01-02T09:19:15.0Z
Creation Date: 2017-11-20T14:00:10.0Z
Registry Expiry Date: 2019-11-20T23:59:59.0Z
Registrar: FBS Inc.
Registrar IANA ID: 1110
Domain Status: pendingDelete https://icann.org/epp#pendingDelete
Domain Status: serverHold https://icann.org/epp#serverHold
...
Name Server: EXPIRED1.DNSENABLE.COM
Name Server: EXPIRED2.DNSENABLE.COM
```

### All Submissions
  - [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
  - [X] Have you checked to ensure there aren't other open
	  [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	  the same update/change?
  - [ ] Added ScreenDump for prove of False Positive
  - [X] Have you added an explanation of what your submission do and why
	  you'd like us to include them??

### Testing face
  - [X] Checked the internet for verification?
  - [X] Have you successfully ran tests with your changes locally?

### Todo:
  - [X] RPZ Server (Team @Spirillen)
  - [X] Added to Source file

Copy of: https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1785
