### ISSUE TITLE
adtube.de

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#81]
## Summary
I believe this domain is an AdWare domain(s) --> that have to be 
blocked as..

- [X] [Wildcarded](source/adware/wildcard.list)
- [ ] [Single domain blocking](source/adware/domains.list)

```python
ads.adtube.de   CNAME . ; AdWare
*.ads.adtube.de   CNAME . ; AdWare
```

## Relevant logs and/or screenshots
```
curl -I ads.adtube.de
HTTP/1.1 302 Found
Date: Sat, 25 Jan 2020 16:31:37 GMT
Server: Apache/2.4.23 (Unix) OpenSSL/1.0.2k-fips
X-Powered-By: PHP/7.3.12
Location: https://google.com
Content-Type: text/html; charset=UTF-8
```

```
curl -I www.ads.adtube.de
HTTP/1.1 302 Found
Date: Sat, 25 Jan 2020 16:33:16 GMT
Server: Apache/2.4.23 (Unix) OpenSSL/1.0.2k-fips
X-Powered-By: PHP/7.3.12
Location: https://google.com
Content-Type: text/html; charset=UTF-8
```

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo
- [x] RPZ Server (Team @Spirillen)
- [X] Added to Source file

CC: https://www.mypdns.org/ticket/168
